# Data cleaning 3.0

In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv(r"H:\DALearning\PythonCodes\PythonLearning\Z-Projects (DA)\Election-2082\2. data_wrangling\2.2 data_assessing_and_cleaning\cleaned_data.csv")

In [3]:
df.head()

,Unnamed: 0,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,...,spouse,experience,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude
0,0,339933,Khitiz Thebe,Nepal Communist Party (Ekikrit Marxbadi Leninb...,2598.0,13962,M,True,भुपेन्द्र थेबे,स्नातक,...,NaN,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667
1,1,341131,Gajendra Prasad Tumyang Limbu,Nepali Congress,2583.0,11711,M,False,Purna Bahadur Limbu,स्नातक,...,Radhika Lingden Tumyang,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667
2,2,339610,Khel Prasad Buda Chhetri,Nepali Communist Party,2557.0,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,...,कुमारी बुडाक्षेत्री,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Higher Secondary / Intermediate (10+2 / PCL),27.35,87.6667
3,3,340005,Santosh Rai,Shram Sanskriti Party,2501.0,5209,M,False,Bal Bahadur Rai,कक्षा ८,...,Sita Rai,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Basic Education (Up to Grade 8),27.35,87.6667
4,4,340459,Birendra Shrestha,Rastriya Swatantra Party,2528.0,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,...,Manolak Wuphashree Shrestha,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          3406 non-null   int64
 1   candidate_id        3406 non-null   int64
 2   candidate           3406 non-null   object
 3   party               3406 non-null   object
 4   party_id            2263 non-null   float64
 5   votes               3406 non-null   int64
 6   gender              3406 non-null   object
 7   is_winner           3406 non-null   bool
 8   father              3405 non-null   object
 9   qualification       2762 non-null   object
 10  institution         1769 non-null   object
 11  address             3406 non-null   object
 12  spouse              2595 non-null   object
 13  experience          1083 non-null   object
 14  province            3406 non-null   object
 15  district            3406 non-null   object
 16  constituency        3406 non-null   object
 17  votes_cast          3406 non-null   int64
 18  total_voters        3406 non-null   int64
 19  education_category  2749 non-null   object
 20  latitude            3406 non-null   float64
 21  longitude           3406 non-null   float64
dtypes: bool(1), float64(3), int64(5), object(13)
memory usage: 562.3+ KB

In [5]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [6]:
df

,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,institution,...,spouse,experience,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude
0,339933,Khitiz Thebe,Nepal Communist Party (Ekikrit Marxbadi Leninb...,2598.0,13962,M,True,भुपेन्द्र थेबे,स्नातक,TU,...,NaN,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667
1,341131,Gajendra Prasad Tumyang Limbu,Nepali Congress,2583.0,11711,M,False,Purna Bahadur Limbu,स्नातक,पाथीभरा वहुमुखी क्याम्पस,...,Radhika Lingden Tumyang,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667
2,339610,Khel Prasad Buda Chhetri,Nepali Communist Party,2557.0,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,TU,...,कुमारी बुडाक्षेत्री,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Higher Secondary / Intermediate (10+2 / PCL),27.35,87.6667
3,340005,Santosh Rai,Shram Sanskriti Party,2501.0,5209,M,False,Bal Bahadur Rai,कक्षा ८,गणेश मा.वि. खेवाङ,...,Sita Rai,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Basic Education (Up to Grade 8),27.35,87.6667
4,340459,Birendra Shrestha,Rastriya Swatantra Party,2528.0,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,युनिभर सिटी आर्मानिय,...,Manolak Wuphashree Shrestha,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3401,339584,Sat‍yanarayana Shreshth,Rastriya Janamorcha,2522.0,170,M,False,चित्रबहादुर श्रेष्ठ,आठ कक्षा उतिर्ण,श्री मा.वि. थवाङ्ग,...,शीतली माया श्रेष्ठ,NaN,Karnali,Rukum West,Rukum West-1,59523,106650,Basic Education (Up to Grade 8),28.65,82.4500
3402,341508,Narendra Ke.si,Ujyalo Nepal Party,2566.0,84,M,False,पुस्प्रसिंह के.सी,स्नातकोत्तर,त्रि.वि.वि./ खुला बिश्वविद्यालय भारत,...,विणा शर्मा,राष्ट्रिय अन्तर्राष्ट्रिय गैरसरकारी संस्थामा २...,Karnali,Rukum West,Rukum West-1,59523,106650,Master's Degree,28.65,82.4500
3403,341627,Shera Bahadura Ke.si.,Nepal Communist Party (Sanyukta),2601.0,54,M,False,दिलबहादुर के.सी.,प्रमाणपत्र तह,NaN,...,"तुल्सीर पुष्पा,टेका के.सी.",शिक्षा सास्त्र संस्थान नेपालगञ्ज,Karnali,Rukum West,Rukum West-1,59523,106650,Higher Secondary / Intermediate (10+2 / PCL),28.65,82.4500
3404,341758,Prema Damaee Nepali,Aam Janata Party (Ekal Chunab Chinha),2581.0,45,F,False,धर्मे दमाई,आधारभुत तह,जनजागृति मा.वि. साँख,...,दलवहादुर नेपाली,10 वर्ष राजनितकअनुभव,Karnali,Rukum West,Rukum West-1,59523,106650,Basic Education (Up to Grade 8),28.65,82.4500
3405,340480,Dhana Bahadura Vi.ka.,Nepal Majdur Kisan Party,2578.0,15,M,False,जसी कामी,प्रमाणपत्र तह,त्रिभुवन विश्वविद्यालय,...,जानकी सुनार,ने.म.कि.पा.मा विगत २५ वर्षदेखि क्रियासिल,Karnali,Rukum West,Rukum West-1,59523,106650,Higher Secondary / Intermediate (10+2 / PCL),28.65,82.4500

## Candidates photo dataframe

In [7]:
cid = df['candidate_id'].unique()

In [8]:
photos = []
for i in cid:
    photos.append(f"https://result.election.gov.np/Images/Candidate/{i}.jpg")

In [9]:
photos_df = pd.DataFrame(data={'candidate_id':cid, 'candidate_photo':photos})

## Parties symbol dataframe

In [10]:
pid = df['party_id'].unique()

In [11]:
pid = pid[~np.isnan(pid)].astype(int)

In [12]:
symbols = []
for i in pid:
    symbols.append(f"https://result.election.gov.np/Images/symbol-hor-pa/{i}.jpg?v=0.2")

In [13]:
symbols_df = pd.DataFrame(data={'party_id':pid, 'party_symbol':symbols})

## Merge `df`, `photos_df`, and `symbols_df`

In [14]:
df = df.merge(photos_df, how='inner', on='candidate_id').merge(symbols_df, how='left', on='party_id')

In [15]:
df

,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,institution,...,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude,candidate_photo,party_symbol
0,339933,Khitiz Thebe,Nepal Communist Party (Ekikrit Marxbadi Leninb...,2598.0,13962,M,True,भुपेन्द्र थेबे,स्नातक,TU,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1,341131,Gajendra Prasad Tumyang Limbu,Nepali Congress,2583.0,11711,M,False,Purna Bahadur Limbu,स्नातक,पाथीभरा वहुमुखी क्याम्पस,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
2,339610,Khel Prasad Buda Chhetri,Nepali Communist Party,2557.0,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,TU,...,Koshi,Taplejung,Taplejung-1,42897,90308,Higher Secondary / Intermediate (10+2 / PCL),27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3,340005,Santosh Rai,Shram Sanskriti Party,2501.0,5209,M,False,Bal Bahadur Rai,कक्षा ८,गणेश मा.वि. खेवाङ,...,Koshi,Taplejung,Taplejung-1,42897,90308,Basic Education (Up to Grade 8),27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
4,340459,Birendra Shrestha,Rastriya Swatantra Party,2528.0,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,युनिभर सिटी आर्मानिय,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3401,339584,Sat‍yanarayana Shreshth,Rastriya Janamorcha,2522.0,170,M,False,चित्रबहादुर श्रेष्ठ,आठ कक्षा उतिर्ण,श्री मा.वि. थवाङ्ग,...,Karnali,Rukum West,Rukum West-1,59523,106650,Basic Education (Up to Grade 8),28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3402,341508,Narendra Ke.si,Ujyalo Nepal Party,2566.0,84,M,False,पुस्प्रसिंह के.सी,स्नातकोत्तर,त्रि.वि.वि./ खुला बिश्वविद्यालय भारत,...,Karnali,Rukum West,Rukum West-1,59523,106650,Master's Degree,28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3403,341627,Shera Bahadura Ke.si.,Nepal Communist Party (Sanyukta),2601.0,54,M,False,दिलबहादुर के.सी.,प्रमाणपत्र तह,NaN,...,Karnali,Rukum West,Rukum West-1,59523,106650,Higher Secondary / Intermediate (10+2 / PCL),28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3404,341758,Prema Damaee Nepali,Aam Janata Party (Ekal Chunab Chinha),2581.0,45,F,False,धर्मे दमाई,आधारभुत तह,जनजागृति मा.वि. साँख,...,Karnali,Rukum West,Rukum West-1,59523,106650,Basic Education (Up to Grade 8),28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3405,340480,Dhana Bahadura Vi.ka.,Nepal Majdur Kisan Party,2578.0,15,M,False,जसी कामी,प्रमाणपत्र तह,त्रिभुवन विश्वविद्यालय,...,Karnali,Rukum West,Rukum West-1,59523,106650,Higher Secondary / Intermediate (10+2 / PCL),28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...

In [16]:
new_name = {
  "Nepal Communist Party (Ekikrit Marxbadi Leninbadi)": "CPN-UML",
  "Swatantra": "Independent",
  "Nagarik Sarbochchata Party Nepal (Ekal Chunab Chinha)": "Nagarik Sarwochata Party Nepal (Ekal Chunab Chinha)",
  "Nepal Janata Sanrakshan Party": "Nepal Janata Samrakchhyan Party",
  "Nepal Sanghiya Samajbadi Party (Ekal Chunab Chinha)": "Nepal Sangyhia Samajbadi Party (Ekal Chunab Chinha)",
  "Jan Adhikar Party": "Jana Adhikar Party",
  "Nepal Matribhumi Party": "Nepal Matribhoomi Party",
  "Rastriya Mukti Andolan, Nepal": "Rastriya Mukti Aandolan, Nepal",
  "Trimul Nepal": "Triumul Nepal",
  "Nepal Communist Party (Marxbadi) (Ekal Chunab Chinha)": "Nepal Communist Party (Marxist) (Ekal Chunab Chinha)",
  "Nagarik Unmukti Party, Nepal (Ekal Chunab Chinha)": "Nagarik Unmukti Party",
  "Gandhiwadi Party Nepal": "Gandhibadi Party Nepal",
  "Nepal Manabatabadi Party": "Nepal Manabta Party",
  "Janata Samajbadi Party, Nepal": "Janata Samjbadi Party-Nepal",
  "Ujyalo Nepal Party": "Ujaylo Nepal Party",
  "Nepal Majdur Kisan Party": "Nepal Majdoor Kisan Party",
  "Rastriya Paribartan Party": "Rastriya Pariwartan Party",
  "Nepal Communist Party (Sanyukta)": "Nepal Communist Party (Sainyukta)",
  "Nepal Communist Party Marxbadi (Pushpalal)": "Nepal Communist Party Marxist (Pushpalal)",
  "Nepal Sadbhawana Party": "Nepal Sadbhavana Party",
  "Sanyukta Nagarik Party": "Sainyukta Nagarik Party",
  "Rashtra Nirman Dal Nepal": "Rastra Nirman Dal Nepal",
  "Sarbabhaum Nagarik Party": "Sarbhobham Nagarik Party"
}

In [17]:
df['party'] = df['party'].replace(new_name)

In [18]:
df[df['candidate'] == 'Mahavira Pun']

,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,institution,...,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude,candidate_photo,party_symbol
2775,339417,Mahavira Pun,Independent,NaN,22850,M,False,कृष्ण पुन,Master Degree,"युनिभर्सिटी अफ नेब्रास्का कर्नी, अमेरिका",...,Gandaki,Myagdi,Myagdi-1,43160,86394,Master's Degree,28.5333,83.55,https://result.election.gov.np/Images/Candidat...,NaN

In [19]:
df.loc[2775, 'is_winner'] = True

- *Fixing mistake **Mahavira Pun** is actually won the election from **Independent** side*

## Export `df` into `.csv` file

In [20]:
df.to_csv("cleaned_data_v2.csv", index=False)

# Dashboard works

In [197]:
df = pd.read_csv("cleaned_data_v2.csv")

In [22]:
df.head()

,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,institution,...,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude,candidate_photo,party_symbol
0,339933,Khitiz Thebe,CPN-UML,2598.0,13962,M,True,भुपेन्द्र थेबे,स्नातक,TU,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1,341131,Gajendra Prasad Tumyang Limbu,Nepali Congress,2583.0,11711,M,False,Purna Bahadur Limbu,स्नातक,पाथीभरा वहुमुखी क्याम्पस,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
2,339610,Khel Prasad Buda Chhetri,Nepali Communist Party,2557.0,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,TU,...,Koshi,Taplejung,Taplejung-1,42897,90308,Higher Secondary / Intermediate (10+2 / PCL),27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3,340005,Santosh Rai,Shram Sanskriti Party,2501.0,5209,M,False,Bal Bahadur Rai,कक्षा ८,गणेश मा.वि. खेवाङ,...,Koshi,Taplejung,Taplejung-1,42897,90308,Basic Education (Up to Grade 8),27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
4,340459,Birendra Shrestha,Rastriya Swatantra Party,2528.0,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,युनिभर सिटी आर्मानिय,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   candidate_id        3406 non-null   int64
 1   candidate           3406 non-null   object
 2   party               3406 non-null   object
 3   party_id            2263 non-null   float64
 4   votes               3406 non-null   int64
 5   gender              3406 non-null   object
 6   is_winner           3406 non-null   bool
 7   father              3405 non-null   object
 8   qualification       2762 non-null   object
 9   institution         1769 non-null   object
 10  address             3406 non-null   object
 11  spouse              2595 non-null   object
 12  experience          1083 non-null   object
 13  province            3406 non-null   object
 14  district            3406 non-null   object
 15  constituency        3406 non-null   object
 16  votes_cast          3406 non-null   int64
 17  total_voters        3406 non-null   int64
 18  education_category  2749 non-null   object
 19  latitude            3406 non-null   float64
 20  longitude           3406 non-null   float64
 21  candidate_photo     3406 non-null   object
 22  party_symbol        2263 non-null   object
dtypes: bool(1), float64(3), int64(4), object(15)
memory usage: 588.9+ KB

In [24]:
temp_seri = df.groupby('party')['votes'].mean().sort_values(ascending=False).head(10)

In [25]:
temp_seri

party
Rastriya Swatantra Party          28540.000000
Nepali Congress                   12173.569697
CPN-UML                            9897.310976
Nepali Communist Party             5951.317073
Swabhiman Party                    5702.000000
Shram Sanskriti Party              2788.091743
Janata Samjbadi Party-Nepal        2056.414894
Rastriya Urjashil Party, Nepal     1434.666667
Rastriya Prajatantra Party         1271.595092
Nagarik Unmukti Party              1239.500000
Name: votes, dtype: float64

In [26]:
df.where(cond=temp_seri, other='Other')

,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,institution,...,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude,candidate_photo,party_symbol
0,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
1,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
2,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
3,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
4,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3401,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
3402,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
3403,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
3404,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other
3405,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other,...,Other,Other,Other,Other,Other,Other,Other,Other,Other,Other

### **Rough Code**

In [27]:
import plotly.express as px

In [28]:
# 1. Create a sample DataFrame
data = {
    'Category': ['Apple', 'Apple', 'Banana', 'Banana', 'Banana', 'Orange', 
                 'Cherry', 'Mango', 'Grape', 'Kiwi', 'Melon', 'Peach', 'Pear']
}
df2 = pd.DataFrame(data)

In [29]:
df2

   Category
0     Apple
1     Apple
2    Banana
3    Banana
4    Banana
5    Orange
6    Cherry
7     Mango
8     Grape
9      Kiwi
10    Melon
11    Peach
12     Pear

In [30]:
# 2. Identify the top 5 categories
top_5 = df2['Category'].value_counts().nlargest(5)
top_5

Category
Banana    3
Apple     2
Orange    1
Cherry    1
Mango     1
Name: count, dtype: int64

In [31]:
top_5 = top_5.index
top_5

Index(['Banana', 'Apple', 'Orange', 'Cherry', 'Mango'], dtype='object', name='Category')

In [32]:
# 3. Replace any category NOT in top 5 with 'Others'
df2['Grouped_Category'] = df2['Category'].where(df2['Category'].isin(top_5), 'Others')
df2['Grouped_Category']

0      Apple
1      Apple
2     Banana
3     Banana
4     Banana
5     Orange
6     Cherry
7      Mango
8     Others
9     Others
10    Others
11    Others
12    Others
Name: Grouped_Category, dtype: object

In [33]:
# 4. Count the frequencies of the new grouped categories
pie_data = df2['Grouped_Category'].value_counts().reset_index()
pie_data

  Grouped_Category  count
0           Others      5
1           Banana      3
2            Apple      2
3           Orange      1
4           Cherry      1
5            Mango      1

In [34]:
pie_data.columns

Index(['Grouped_Category', 'count'], dtype='object')

In [35]:
pie_data.columns = ['Category', 'Count']
pie_data.columns

Index(['Category', 'Count'], dtype='object')

In [36]:
# 5. Plot the pie chart using Plotly Express
fig = px.pie(pie_data, values='Count', names='Category', hole=0.5, title='Top 5 Categories vs Others')
fig.show()

#### 1. **Overall**

In [37]:
temp_seri = df.groupby('party')['votes'].sum()

In [38]:
top_5 = temp_seri.nlargest(5)
top_5

party
Rastriya Swatantra Party    4680560
Nepali Congress             2008639
CPN-UML                     1623159
Nepali Communist Party       976016
Shram Sanskriti Party        303902
Name: votes, dtype: int64

In [39]:
top_5.index

Index(['Rastriya Swatantra Party', 'Nepali Congress', 'CPN-UML',
       'Nepali Communist Party', 'Shram Sanskriti Party'],
      dtype='object', name='party')

In [40]:
temp_seri.index.isin(top_5.index)

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False])

In [41]:
temp_seri.index.where(cond=temp_seri.index.isin(top_5.index), other='Others').value_counts()

party
Others                      61
CPN-UML                      1
Nepali Communist Party       1
Nepali Congress              1
Rastriya Swatantra Party     1
Shram Sanskriti Party        1
Name: count, dtype: int64

In [42]:
px.pie(data_frame=temp_seri, values=temp_seri.values, names=temp_seri.index)

In [43]:
temp_seri.nlargest(n=5)

party
Rastriya Swatantra Party    4680560
Nepali Congress             2008639
CPN-UML                     1623159
Nepali Communist Party       976016
Shram Sanskriti Party        303902
Name: votes, dtype: int64

In [44]:
# --- Assuming this is your starting df2 ---
df2 = df.groupby('party')['votes'].sum().reset_index()

# 1. Identify the top 5 parties by votes
top_5_parties = df2.nlargest(n=5, columns='votes')['party'].values

# 2. Inline transformation inside px.pie
fig = px.pie(
    df2.assign(
        party=df2['party'].where(cond=df2['party'].isin(top_5_parties), other='Others')
    ).groupby('party', as_index=False)['votes'].sum(),
    
    values='votes', 
    names='party', 
    title='Top 5 Parties vs Others'
)

fig.show()

In [45]:
df2.assign(
        party=df2['party'].where(cond=df2['party'].isin(top_5_parties), other='Others')
    )

                    party    votes
0                  Others    19742
1                  Others     1606
2                  Others      354
3                 CPN-UML  1623159
4                  Others        4
..                    ...      ...
61  Shram Sanskriti Party   303902
62                 Others    11404
63                 Others       16
64                 Others   115975
65                 Others       32

[66 rows x 2 columns]

In [46]:
# 1. Create a Series with party names as index and votes as values
vote_series = df.groupby('party')['votes'].sum()
# 2. Identify the top 5 parties
top_5 = vote_series.nlargest(5).index

# 3. Transform inline inside px.pie using Series methods
fig = px.pie(
    vote_series
    # Rename index elements outside the top 5 to 'Others'
    .rename(lambda x: x if x in top_5 else 'Others')
    # Sum the duplicates created by 'Others' and reset the index into a DataFrame
    .groupby(level=0).mean().reset_index(name='votes'),
    
    values='votes', 
    names='party', 
    title='Top 5 Parties vs Others (Series Method)'
)

fig.show()

In [206]:
temp_seri = df.groupby('party')['votes'].sum()
top_5 = temp_seri.nlargest(5).index

fig = px.pie(
    temp_seri.rename(lambda x: x if x in top_5 else 'Others').groupby(level=0).mean().reset_index(name='votes'),
    values='votes',
    hole=0.0, 
    hover_name='party', 
    title='Parties Vote Share %'
    )

fig

In [47]:
temp_df = df.groupby(by='party')['votes'].sum().reset_index()

In [48]:
temp_df['rank'] = temp_df['votes'].rank(ascending=False).astype(int)

In [49]:
temp_df.sort_values(by='rank').set_index('party')

                                                      votes  rank
party
Rastriya Swatantra Party                            4680560     1
Nepali Congress                                     2008639     2
CPN-UML                                             1623159     3
Nepali Communist Party                               976016     4
Shram Sanskriti Party                                303902     5
...                                                     ...   ...
Nepal Communist Party (Marxist) (Ekal Chunab Ch...       16    62
Triumul Nepal                                            16    62
Rastriya Janata Party Nepal                              13    64
Rastriya Nagarik Party                                   12    65
Gandhibadi Party Nepal                                    4    66

[66 rows x 2 columns]

In [50]:
temp_seri = df.groupby('party')['votes'].mean().nlargest(n=10)

In [51]:
temp_seri.index

Index(['Rastriya Swatantra Party', 'Nepali Congress', 'CPN-UML',
       'Nepali Communist Party', 'Swabhiman Party', 'Shram Sanskriti Party',
       'Janata Samjbadi Party-Nepal', 'Rastriya Urjashil Party, Nepal',
       'Rastriya Prajatantra Party', 'Nagarik Unmukti Party'],
      dtype='object', name='party')

In [52]:
temp_seri = df[df['party'].isin(temp_seri.index)].groupby('party')['votes'].mean()

In [53]:
px.bar(temp_seri, x=temp_seri.index,y=temp_seri.values, animation_frame=temp_seri.values,animation_group=temp_seri.index)

In [54]:
df

,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,institution,...,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude,candidate_photo,party_symbol
0,339933,Khitiz Thebe,CPN-UML,2598.0,13962,M,True,भुपेन्द्र थेबे,स्नातक,TU,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1,341131,Gajendra Prasad Tumyang Limbu,Nepali Congress,2583.0,11711,M,False,Purna Bahadur Limbu,स्नातक,पाथीभरा वहुमुखी क्याम्पस,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
2,339610,Khel Prasad Buda Chhetri,Nepali Communist Party,2557.0,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,TU,...,Koshi,Taplejung,Taplejung-1,42897,90308,Higher Secondary / Intermediate (10+2 / PCL),27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3,340005,Santosh Rai,Shram Sanskriti Party,2501.0,5209,M,False,Bal Bahadur Rai,कक्षा ८,गणेश मा.वि. खेवाङ,...,Koshi,Taplejung,Taplejung-1,42897,90308,Basic Education (Up to Grade 8),27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
4,340459,Birendra Shrestha,Rastriya Swatantra Party,2528.0,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,युनिभर सिटी आर्मानिय,...,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3401,339584,Sat‍yanarayana Shreshth,Rastriya Janamorcha,2522.0,170,M,False,चित्रबहादुर श्रेष्ठ,आठ कक्षा उतिर्ण,श्री मा.वि. थवाङ्ग,...,Karnali,Rukum West,Rukum West-1,59523,106650,Basic Education (Up to Grade 8),28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3402,341508,Narendra Ke.si,Ujaylo Nepal Party,2566.0,84,M,False,पुस्प्रसिंह के.सी,स्नातकोत्तर,त्रि.वि.वि./ खुला बिश्वविद्यालय भारत,...,Karnali,Rukum West,Rukum West-1,59523,106650,Master's Degree,28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3403,341627,Shera Bahadura Ke.si.,Nepal Communist Party (Sainyukta),2601.0,54,M,False,दिलबहादुर के.सी.,प्रमाणपत्र तह,NaN,...,Karnali,Rukum West,Rukum West-1,59523,106650,Higher Secondary / Intermediate (10+2 / PCL),28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3404,341758,Prema Damaee Nepali,Aam Janata Party (Ekal Chunab Chinha),2581.0,45,F,False,धर्मे दमाई,आधारभुत तह,जनजागृति मा.वि. साँख,...,Karnali,Rukum West,Rukum West-1,59523,106650,Basic Education (Up to Grade 8),28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
3405,340480,Dhana Bahadura Vi.ka.,Nepal Majdoor Kisan Party,2578.0,15,M,False,जसी कामी,प्रमाणपत्र तह,त्रिभुवन विश्वविद्यालय,...,Karnali,Rukum West,Rukum West-1,59523,106650,Higher Secondary / Intermediate (10+2 / PCL),28.65,82.4500,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...

In [55]:
px.scatter_map(df, lat='latitude', lon='longitude', size='votes', color='province', zoom=5, size_max=20, 
                                hover_name='constituency', hover_data=['party','candidate','is_winner'], map_style='carto-positron')

In [56]:
vote_series = df.groupby('constituency')['votes'].sum()
top_10 = vote_series.nlargest(10).index
fig = px.bar(
    vote_series.rename(lambda x: x if x in top_10 else 'Others').groupby(level=0).mean().reset_index(name='votes'),
    x='constituency',
    y='votes',
    labels={'votes':'avg votes'},
    title='Top 10 Constituencies vs Others (Bar Chart)',
)

fig.show()

In [57]:
temp_df = df.query("is_winner == True").groupby(by=['candidate','party','constituency','is_winner'])['votes'].sum().reset_index().nlargest(n=100, columns='votes')

In [58]:
# [(temp_df['is_winner'] == False)]
temp_df

,candidate,party,constituency,is_winner,votes
15,Balendra Shah,Rastriya Swatantra Party,Jhapa-5,True,68348
55,Indira Rana Magar,Rastriya Swatantra Party,Jhapa-2,True,60110
139,Sobita Gautam,Rastriya Swatantra Party,Chitwan-3,True,59277
90,Mohan Thapa,Rastriya Swatantra Party,Rupandehi-3,True,58814
51,Hari Dhakal,Rastriya Swatantra Party,Chitwan-1,True,58208
...,...,...,...,...,...
43,Ganesh Parajuli,Rastriya Swatantra Party,Kathmandu-7,True,27805
21,Bikram Thapa,Rastriya Swatantra Party,Kapilvastu-2,True,27635
148,Sushant Vaidik,Rastriya Swatantra Party,Pyuthan-1,True,27469
16,Barshman Pun,Nepali Communist Party,Rolpa-1,True,27460
162,Yajnyamani Nyaaipane,Rastriya Swatantra Party,Morang-1,True,27367

In [59]:
# round(number=(temp_df['votes'] / df['votes'].sum()) * 100, ndigits=2)

In [60]:
temp_df['rank'] = temp_df['votes'].rank(ascending=False).astype(int)

In [61]:
temp_df.sort_values(by='rank').set_index('candidate')

,party,constituency,is_winner,votes,rank
candidate,,,,,
Balendra Shah,Rastriya Swatantra Party,Jhapa-5,True,68348,1
Indira Rana Magar,Rastriya Swatantra Party,Jhapa-2,True,60110,2
Sobita Gautam,Rastriya Swatantra Party,Chitwan-3,True,59277,3
Mohan Thapa,Rastriya Swatantra Party,Rupandehi-3,True,58814,4
Hari Dhakal,Rastriya Swatantra Party,Chitwan-1,True,58208,5
...,...,...,...,...,...
Ganesh Parajuli,Rastriya Swatantra Party,Kathmandu-7,True,27805,96
Bikram Thapa,Rastriya Swatantra Party,Kapilvastu-2,True,27635,97
Sushant Vaidik,Rastriya Swatantra Party,Pyuthan-1,True,27469,98
Barshman Pun,Nepali Communist Party,Rolpa-1,True,27460,99
Yajnyamani Nyaaipane,Rastriya Swatantra Party,Morang-1,True,27367,100

In [62]:
temp_df = df.groupby(['constituency', 'party'], as_index=False)['votes'].sum()

# Identify top 10 constituencies by total votes
top_10_const = (
    df.groupby('constituency')['votes'].sum().nlargest(10).index
)

# Replace constituencies not in top 10 with 'Others'
temp_df['constituency_grouped'] = temp_df['constituency'].apply(
    lambda x: x if x in top_10_const else 'Others'
)

# Aggregate to find the average votes for the grouped categories
plot_df = (
    temp_df.groupby(['constituency_grouped', 'party'], as_index=False)[
        'votes'
    ]
    .mean()
    .rename(columns={'constituency_grouped': 'constituency'})
)

fig = px.bar(
    plot_df,
    x='constituency',
    y='votes',
    color='party',
    labels={'votes': 'avg votes'},
    title='Top 10 Constituencies vs Others (Bar Chart)',
)
fig.show()

In [63]:
# temp_df = df.groupby(['constituency', 'party'], as_index=False)['votes'].sum()
# top_10 = df.groupby('constituency')['votes'].sum().nlargest(10).index
# temp_df['constituency_grouped'] = temp_df['constituency'].apply(lambda x: x if x in top_10 else 'Others')

# plot_df = temp_df.groupby(['constituency_grouped', 'party'], as_index=False)['votes'].mean().rename(columns={'constituency_grouped': 'constituency'})

# fig = px.bar(
#     plot_df,
#     x='constituency',
#     y='votes',
#     color='party',
#     labels={'votes': 'avg votes'},
#     title='Top 10 Constituencies vs Others (Bar Chart)',
# )
# fig.show()

In [64]:
# 1. Find the top 10 constituencies and top 5 parties globally
top_10_const = df.groupby('constituency')['votes'].sum().nlargest(10).index
top_5_parties = df.groupby('party')['votes'].sum().nlargest(5).index

# 2. Sum votes by constituency and party to avoid duplicate rows
temp_df = df.groupby(['constituency', 'party'], as_index=False)['votes'].sum()

# 3. Mask values outside the top groups as 'Others'
temp_df['const_grouped'] = temp_df['constituency'].apply(lambda x: x if x in top_10_const else 'Others')
temp_df['party_grouped'] = temp_df['party'].apply(lambda x: x if x in top_5_parties else 'Others')

# 4. Aggregate by the new grouped columns
plot_df = temp_df.groupby(['const_grouped', 'party_grouped'], as_index=False)['votes'].mean()

# 5. Rename columns for clean plot labels
plot_df = plot_df.rename(columns={'const_grouped': 'constituency', 'party_grouped': 'party'})

# 6. Plot the dynamic stacked bar chart
fig = px.bar(
    plot_df,
    x='constituency',
    y='votes',
    color='party',
    labels={'votes': 'avg votes'},
    title='Top 10 Constituencies vs Others by Top 5 Parties vs Others',
    category_orders={
        'constituency': list(top_10_const) + ['Others'],
        'party': list(top_5_parties) + ['Others']
    }
)
fig.show()

In [65]:
# top_10_const = df.groupby('constituency')['votes'].sum().nlargest(10).index
# top_5_parties = df.groupby('party')['votes'].sum().nlargest(5).index

# temp_df = df.groupby(['constituency', 'party'], as_index=False)['votes'].sum()

# temp_df['const_grouped'] = temp_df['constituency'].apply(lambda x: x if x in top_10_const else 'Others')
# temp_df['party_grouped'] = temp_df['party'].apply(lambda x: x if x in top_5_parties else 'Others')

# plot_df = temp_df.groupby(['const_grouped', 'party_grouped'], as_index=False)['votes'].mean()
# plot_df = plot_df.rename(columns={'const_grouped': 'constituency', 'party_grouped': 'party'})

# fig = px.bar(
#     plot_df,
#     x='constituency',
#     y='votes',
#     color='party',
#     labels={'votes': 'avg votes'},
#     title='Top 10 Constituencies vs Others by Top 5 Parties vs Others',
#     category_orders={
#         'constituency': list(top_10_const) + ['Others'],
#         'party': list(top_5_parties) + ['Others']
#     }
# )
# fig.show()

In [66]:
temp_df = df.groupby('constituency')[['votes_cast','total_voters']].head(1)

In [67]:
round((temp_df['votes_cast'].sum() / temp_df['total_voters'].sum()) * 100, 2)

np.float64(55.86)

In [68]:
round((df.query("gender == 'F'")['votes'].mean() / df['votes'].mean()) * 100, 2)

np.float64(71.05)

In [69]:
round((df.query("gender == 'M'")['votes'].mean() / df['votes'].mean()) * 100, 2)

np.float64(103.72)

In [70]:
round(df.query("gender == 'F'")['votes'].mean(), 2)

np.float64(2202.54)

In [71]:
round(df.query("gender == 'M'")['votes'].mean(), 2)

np.float64(3215.52)

In [72]:
df.query("gender == 'F'")['candidate'].count()

np.int64(388)

In [73]:
df.query("gender == 'M'")['candidate'].count()

np.int64(3018)

#### 2. **Party-wise**

In [74]:
df.query("party == 'Rastriya Swatantra Party'")['party_symbol'].unique()[0]

'https://result.election.gov.np/Images/symbol-hor-pa/2528.jpg?v=0.2'

In [75]:
df.groupby('party')['votes'].mean().rank(ascending=False)

party
Aam Janata Party (Ekal Chunab Chinha)             27.0
Bahujan Ekata Party Nepal (Ekal Chunab Chinha)    25.0
Bahujan Shakti Party                              37.0
CPN-UML                                            3.0
Gandhibadi Party Nepal                            66.0
                                                  ...
Shram Sanskriti Party                              6.0
Swabhiman Party                                    5.0
Triumul Nepal                                     65.0
Ujaylo Nepal Party                                11.0
United Nepal Democratic Party                     59.5
Name: votes, Length: 66, dtype: float64

In [76]:
temp_df2 = df.groupby(by=['party'])['votes'].sum().reset_index()

In [77]:
temp_df2['party_rank'] = temp_df2['votes'].rank(ascending=False).astype(int)

In [78]:
temp_df2.sort_values(by='party_rank')

                                                party    votes  party_rank
54                           Rastriya Swatantra Party  4680560           1
35                                    Nepali Congress  2008639           2
3                                             CPN-UML  1623159           3
34                             Nepali Communist Party   976016           4
61                              Shram Sanskriti Party   303902           5
..                                                ...      ...         ...
21  Nepal Communist Party (Marxist) (Ekal Chunab C...       16          62
63                                      Triumul Nepal       16          62
47                        Rastriya Janata Party Nepal       13          64
50                             Rastriya Nagarik Party       12          65
4                              Gandhibadi Party Nepal        4          66

[66 rows x 3 columns]

In [79]:
party_rank = temp_df2[temp_df2['party'] == 'Rastriya Swatantra Party']['party_rank']

In [80]:
print("#",party_rank.values[0])

# 1

In [81]:
temp_df2[temp_df2['party'] == 'Rastriya Swatantra Party']['votes'] / df['votes'].sum()

54    0.443276
Name: votes, dtype: float64

In [82]:
temp_df

      votes_cast  total_voters
0          42897         90308
13         66921        143358
28         59391        112296
41         63781        119475
55         78291        130993
...          ...           ...
3303       61117        109572
3322       53546        103087
3339       77089        123072
3365       83456        131049
3394       59523        106650

[165 rows x 2 columns]

In [83]:
df.query("party == 'Rastriya Swatantra Party'").groupby('constituency')['votes'].sum().nlargest(10)

constituency
Jhapa-5        68348
Jhapa-2        60110
Chitwan-3      59277
Rupandehi-3    58814
Chitwan-1      58208
Sunsari-2      57348
Rupandehi-2    56550
Morang-6       55513
Rupandehi-1    54845
Chitwan-2      54402
Name: votes, dtype: int64

In [84]:
temp_df = df.query("party == 'Rastriya Swatantra Party'")

In [85]:
# top_10_const = temp_df.groupby('constituency')['votes'].sum().nlargest(10).index
# provinces = temp_df.groupby('province')['votes'].sum().nlargest(5).index

# temp_df = temp_df.groupby(['constituency', 'province'], as_index=False)['votes'].sum()

# temp_df['const_grouped'] = temp_df['constituency'].apply(lambda x: x if x in top_10_const else 'Others')
# temp_df['province_grouped'] = temp_df['province'].apply(lambda x: x if x in provinces else 'Others')

# plot_df = temp_df.groupby(['const_grouped', 'province_grouped'], as_index=False)['votes'].mean()
# plot_df = plot_df.rename(columns={'const_grouped': 'constituency', 'province_grouped': 'province'})

# fig = px.bar(
#     plot_df,
#     x='constituency',
#     y='votes',
#     color='province',
#     labels={'votes': 'avg votes'},
#     title='Top 10 Constituencies vs Others by Top 5 Parties vs Others',
#     category_orders={
#         'constituency': list(top_10_const) + ['Others'],
#         'province': list(provinces) + ['Others']
#     }
# )
# fig.show()

In [86]:
vote_series = temp_df.groupby('constituency')['votes'].sum()
top_10 = vote_series.nlargest(10).index
fig = px.bar(
    vote_series.rename(lambda x: x if x in top_10 else 'Others').groupby(level=0).mean().reset_index(name='votes'),
    x='constituency',
    y='votes',
    labels={'votes':'avg votes'},
    title='Top 10 Constituencies vs Others (Bar Chart)',
)

fig.show()

In [87]:
symbol_url = df[df['party'] == 'Independent']['party_symbol'].unique()[0]

In [88]:
if pd.notna(symbol_url):
    print("Party Symbol")
else:
    print("🧑")

🧑

In [ ]:
(df[df['candidate'] == 'Durga Prasad Sawa Limbu']['is_winner'] == True).values

np.False_

In [90]:
df['party'].unique()

array(['CPN-UML', 'Nepali Congress', 'Nepali Communist Party',
       'Shram Sanskriti Party', 'Rastriya Swatantra Party',
       'Ujaylo Nepal Party', 'Sanghiya Loktantrik Rastriya Manch',
       'Rastriya Prajatantra Party', 'Nepal Communist Party (Maoist)',
       'Janata Samajbadi Party (Ekal Chunab Chinha)',
       'Janata Samjbadi Party-Nepal', 'Mongol National Organization',
       'Nepal Janamukti Party', 'Rastriya Pariwartan Party',
       'Rastriya Mukti Party Nepal (Ekal Chunab Chinha)',
       'Pragatishil Loktantrik Party', 'Nepal Majdoor Kisan Party',
       'Rastriya Janamukti Party', 'Independent',
       'Nepal Sadbhavana Party', 'Janamat Party',
       'Nepal Communist Party (Sainyukta)', 'National Republic Nepal',
       'Nepal Communist Party Marxist (Pushpalal)', 'People First Party',
       'Rastriya Janamorcha', 'Nepali Janashramdan Sanskriti Party',
       'Aam Janata Party (Ekal Chunab Chinha)', 'Miteri Party Nepal',
       'Rastriya Urjashil Party, Nepal', 'Sainyukta Nagarik Party',
       'Jaya Matribhumi Party', 'Rastra Nirman Dal Nepal',
       'Samabeshi Samajbadi Party', 'Nagarik Unmukti Party',
       'Sarbhobham Nagarik Party', 'Rastriya Sajha Party',
       'Nepal Loktantrik Party', 'Samabeshi Samajbadi Party Nepal',
       'Nepal Janata Party', 'Nepali Janata Dal',
       'Nagarik Sarwochata Party Nepal (Ekal Chunab Chinha)',
       'Swabhiman Party', 'Nepal Janata Samrakchhyan Party',
       'Rastriya Ekata Dal', 'Jana Adhikar Party',
       'Nepalka Lagi Nepali Party', 'Janata Loktantrik Party, Nepal',
       'Nepal Sangyhia Samajbadi Party (Ekal Chunab Chinha)',
       'Bahujan Ekata Party Nepal (Ekal Chunab Chinha)',
       'Bahujan Shakti Party', 'Itihasik Janata Party',
       'Janadesh Party Nepal (Ekal Chunab Chinha)',
       'Rastriya Janata Party Nepal', 'Rastriya Mukti Aandolan, Nepal',
       'Gatishil Loktantrik Party', 'United Nepal Democratic Party',
       'Prajatantrik Party Nepal', 'Nepal Janasewa Party',
       'Triumul Nepal',
       'Nepal Communist Party (Marxist) (Ekal Chunab Chinha)',
       'Rastriya Nagarik Party', 'Nepal Manabta Party',
       'Nepal Matribhoomi Party', 'Gandhibadi Party Nepal',
       'Rastriya Janamat Party'], dtype=object)

#### 3. **Candidate-wise**

In [95]:
df[df['candidate'] == 'Aalam Kawari']['candidate_photo'].values[0]

'https://result.election.gov.np/Images/Candidate/341315.jpg'

In [113]:
df[df['constituency'] == 'Kavrepalanchok-2']

,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,institution,...,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude,candidate_photo,party_symbol
1726,339525,Badana Kumara Bhandari,Rastriya Swatantra Party,2528.0,53344,M,True,चुरा बहादुर भण्डारी,+2,HSEB,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Higher Secondary / Intermediate (10+2 / PCL),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1727,340524,Madhu Prasada Aachary,Nepali Congress,2583.0,17868,M,False,धुर्व प्रसाद आचार्य,स्नातकोत्तर,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Master's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1728,339988,Ashoka Kumara Byanyju Shreshth,CPN-UML,2598.0,13940,M,False,वच्चु नाथ ब्याञ्जु,BA,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Bachelor's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1729,341012,Basundhara Humagaee,Nepali Communist Party,2557.0,8107,M,False,नारायण प्रसाद हुमागाई,I A,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Higher Secondary / Intermediate (10+2 / PCL),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1730,340306,Jyotsana Saiju,Ujaylo Nepal Party,2566.0,3749,F,False,ज्योती प्रकाश सैजु,BA कम्प्युटर इन्जिनियरिङ,KU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,NaN,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1731,342166,Ranjiva Shreshth,Rastriya Prajatantra Party,2604.0,1125,M,False,भिम सुन्दर श्रेष्ठ,स्नातकोत्तर,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Master's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1732,339321,Muna Tamang,Nepal Majdoor Kisan Party,2578.0,428,F,False,कृष्‍ण बहादुर तामाङ,MA,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Master's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1733,342232,Tanka Bahadura Lama,Shram Sanskriti Party,2501.0,400,M,False,ज्ञान ध्वज लामा,स्नातकोत्तर,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Master's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1734,340432,Kanchha Rama Ghising,Nepal Communist Party (Maoist),2526.0,146,M,False,कृष्ण बहादुर तामाङ,साधारण लेखपढ,NaN,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Literate / Non-Formal,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1735,342107,Ramesha Bahadura Gharti Kshetri,Pragatishil Loktantrik Party,2516.0,144,M,False,कुल बहादुर घर्ति क्षेत्री,साक्षर,NaN,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Literate / Non-Formal,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1736,340908,Aasa Tamang,Independent,NaN,59,F,False,शंखर तामाङ,+2,HSEB,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Higher Secondary / Intermediate (10+2 / PCL),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,NaN
1737,340675,Suvarna Vikrama Thapa,Rastriya Janamorcha,2522.0,39,M,False,शिवजी थापा,SLC,SLC BOard,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Secondary Education (Grade 9-10 / SLC / SEE),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1738,340247,Rakama Lama (tamanga),Janata Samjbadi Party-Nepal,2542.0,32,M,False,बिर बहादुर तामाङ,SLC,SLC Board,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Secondary Education (Grade 9-10 / SLC / SEE),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1739,340610,Rajana Thapa,Nepal Communist Party (Sainyukta),2601.0,32,M,False,तेज बहादुर थापा,I L,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Higher Secondary / Intermediate (10+2 / PCL),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1740,339436,Dilliprasada Nyaupane,Independent,NaN,31,M,False,बुद्धिप्रसाद न्यौपाने,स्नातकोत्तर,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Master's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,NaN
1741,340826,Umesha Tamang,Mongol National Organization,2511.0,28,M,False,अशोक तामाङ,९ कक्षा,श्री कालिका माध्यामिक विद्यालय,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Secondary Education (Grade 9-10 / SLC / SEE),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1742,341614,Umesa Thapa,Independent,NaN,26,M,False,प्रेम बहादुर थापा,स्नातक,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Bachelor's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,NaN
1743,341827,Sita Rama Mainali,Independent,NaN,21,M,False,बेनी प्रसाद मैनाली,SLC,SLC Board,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Secondary Education (Grade 9-10 / SLC / SEE),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,NaN
1744,340088,Sukamana Tamad,National Republic Nepal,2504.0,15,M,False,व्रथा तामाङ,साधारण लेखपढ,NaN,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Literate / Non-Formal,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1745,342279,Vishnu Kumara Shresh‍th,Independent,NaN,13,M,False,नर मान श्रेष्‍ठ,साक्षर,NaN,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Literate / Non-Formal,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,NaN
1746,341536,Ganesha Prasada Adhikari,Independent,NaN,11,M,False,बद्री प्रसाद अधिकारी,स्नातक,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Bachelor's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,NaN
1747,341213,Hari Bahadura Thapa,Miteri Party Nepal,2530.0,10,M,False,चक्र बहादुर थापा,साक्षर,NaN,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Literate / Non-Formal,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
1748,341904,Lenina Vish‍ta,Independent,NaN,8,M,False,श्याम काजी विष्‍ट,MA,TU,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Master's Degree,27.5667,85.5,https://result.election.gov.np/Images/Candidat...,NaN
1749,341738,Keshavaraja Timalsina,Independent,NaN,4,M,False,बेल प्रसाद तिमल्सिना,SLC,SLC BOARD,...,Bagmati,Kavrepalanchok,Kavrepalanchok-2,99580,165485,Secondary Education (Grade 9-10 / SLC / SEE),27.5667,85.5,https://result.election.gov.np/Images/Candidat...,NaN

In [116]:
temp_df = df[df['candidate'] == 'Balendra Shah']

In [127]:
temp_df['votes']

121    68348
Name: votes, dtype: int64

In [141]:
round(temp_df['votes'] / df[df['constituency' ] == temp_df['constituency'].values[0]]['votes'].sum() * 100, 2).values[0]

np.float64(66.79)

In [136]:
df[df['constituency' ] == temp_df['constituency'].values[0]]

,candidate_id,candidate,party,party_id,votes,gender,is_winner,father,qualification,institution,...,province,district,constituency,votes_cast,total_voters,education_category,latitude,longitude,candidate_photo,party_symbol
121,339653,Balendra Shah,Rastriya Swatantra Party,2528.0,68348,M,True,Ram Narayan Shah,BTU,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Bachelor's Degree,26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
122,340111,KP Sharma Oli,CPN-UML,2598.0,18734,M,False,मोहन प्रसाद ओली,NaN,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,NaN,26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
123,342365,Samir Tamang,Shram Sanskriti Party,2501.0,9233,M,False,Dhan Bahadur Tamang,10+2,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Higher Secondary / Intermediate (10+2 / PCL),26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
124,340445,Mandhara Chimariya,Nepali Congress,2583.0,1821,F,False,Lal Bahadur Chimariya,SLC,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Secondary Education (Grade 9-10 / SLC / SEE),26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
125,339386,Laxmi Prasad Sangroula,Rastriya Prajatantra Party,2604.0,1536,M,False,श्रीप्रसाद संग्रौला,आइ ए,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Higher Secondary / Intermediate (10+2 / PCL),26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
126,340171,Ranjit Tamang,Nepali Communist Party,2557.0,1461,M,False,Lok Bahadur Tamang,NaN,TU,...,Koshi,Jhapa,Jhapa-5,102338,163356,NaN,26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
127,340730,Amritlal Mahto,Janamat Party,2585.0,296,M,False,नन्दलाल महतो,SLC,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Secondary Education (Grade 9-10 / SLC / SEE),26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
128,339687,Sushant Sampang Rai,Rastriya Pariwartan Party,2568.0,204,M,False,Shyam Kumar Rai,NaN,TU,...,Koshi,Jhapa,Jhapa-5,102338,163356,NaN,26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
129,339421,San Bahadur Meche,Mongol National Organization,2511.0,166,M,False,Nandalal Meche,10+2,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Higher Secondary / Intermediate (10+2 / PCL),26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
130,341042,Shobha Bhandari,Independent,NaN,82,F,False,Ram Bahadur Magar,SLC,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Secondary Education (Grade 9-10 / SLC / SEE),26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN
131,341101,Sanjay Rai,Nepal Communist Party (Maoist),2526.0,76,M,False,Bhal Bahadur Rai,BBS,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Bachelor's Degree,26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
132,340581,Padam Bahadur Javegu,Nepal Janamukti Party,2529.0,72,M,False,श्री प्रसाद जवेगु,BBS,TU,...,Koshi,Jhapa,Jhapa-5,102338,163356,Bachelor's Degree,26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
133,341500,Sushant Sampang Rai,Sanghiya Loktantrik Rastriya Manch,2550.0,72,M,False,Shyam Kumar Rai,bachelor,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Bachelor's Degree,26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
134,341745,Dhiren Subba,Janata Samjbadi Party-Nepal,2542.0,42,M,False,Chhatrasingh Lawati,10+2,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Higher Secondary / Intermediate (10+2 / PCL),26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
135,340964,Amrit Rasaili,Rastriya Mukti Party Nepal (Ekal Chunab Chinha),2531.0,35,M,False,Buddhiman Rasaili,SLC,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Secondary Education (Grade 9-10 / SLC / SEE),26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
136,339300,Dharmraj Guragain,People First Party,2552.0,34,M,False,नर प्रसाद गुरागाई,10+2,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Higher Secondary / Intermediate (10+2 / PCL),26.55,87.7,https://result.election.gov.np/Images/Candidat...,https://result.election.gov.np/Images/symbol-h...
137,342521,Khemnath Shiwakoti,Independent,NaN,25,M,False,Chandra Prasad Shiwakoti,SLC,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Secondary Education (Grade 9-10 / SLC / SEE),26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN
138,342687,Damvara Shahu,Independent,NaN,24,M,False,सिउले शाहु,स्नात्कोत्तर,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Master's Degree,26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN
139,342498,Puskar Khatiwada,Independent,NaN,24,M,False,सेतु खतिवडा,आचार्य,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Master's Degree,26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN
140,341971,Bipul Guragain,Independent,NaN,19,M,False,Yagya Prasad Guragai,10+2,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Higher Secondary / Intermediate (10+2 / PCL),26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN
141,341581,Arjun Sapkota,Independent,NaN,15,M,False,Prajapati Sapkota,SLC,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Secondary Education (Grade 9-10 / SLC / SEE),26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN
142,342192,Ranjana Gautam,Independent,NaN,10,F,False,Kamalpati Gautam,10+2,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Higher Secondary / Intermediate (10+2 / PCL),26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN
143,339787,Matrika Bhattarai,Independent,NaN,6,M,False,Padam Prasad Bhattarai,NaN,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,NaN,26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN
144,341230,Prakash Nepal,Independent,NaN,3,M,False,Dambar Prasad Nepal,10+2,NaN,...,Koshi,Jhapa,Jhapa-5,102338,163356,Higher Secondary / Intermediate (10+2 / PCL),26.55,87.7,https://result.election.gov.np/Images/Candidat...,NaN

In [143]:
temp_df.columns

Index(['candidate_id', 'candidate', 'party', 'party_id', 'votes', 'gender',
       'is_winner', 'father', 'qualification', 'institution', 'address',
       'spouse', 'experience', 'province', 'district', 'constituency',
       'votes_cast', 'total_voters', 'education_category', 'latitude',
       'longitude', 'candidate_photo', 'party_symbol'],
      dtype='object')

In [172]:
rivals = df[df['constituency'] == temp_df['constituency'].values[0]].nlargest(6, 'votes')[['candidate','party','votes']][1:].set_index('candidate')

In [173]:
rivals

                                             party  votes
candidate
KP Sharma Oli                              CPN-UML  18734
Samir Tamang                 Shram Sanskriti Party   9233
Mandhara Chimariya                 Nepali Congress   1821
Laxmi Prasad Sangroula  Rastriya Prajatantra Party   1536
Ranjit Tamang               Nepali Communist Party   1461

In [164]:
def extract_rival(row):
    return(row['candidate'])

# rivals.apply(extract_rival, axis=1)

In [165]:
rivals.apply(extract_rival, axis=1)

121             Balendra Shah
122             KP Sharma Oli
123              Samir Tamang
124        Mandhara Chimariya
125    Laxmi Prasad Sangroula
dtype: object

In [176]:
rivals = df[df['constituency'] == temp_df['constituency'].values[0]][['candidate','party','votes']]

In [182]:
rivals[~(rivals['candidate'] == 'Balendra Shah')].nlargest(5, 'votes')

                  candidate                       party  votes
122           KP Sharma Oli                     CPN-UML  18734
123            Samir Tamang       Shram Sanskriti Party   9233
124      Mandhara Chimariya             Nepali Congress   1821
125  Laxmi Prasad Sangroula  Rastriya Prajatantra Party   1536
126           Ranjit Tamang      Nepali Communist Party   1461

In [184]:
temp_df.columns

Index(['candidate_id', 'candidate', 'party', 'party_id', 'votes', 'gender',
       'is_winner', 'father', 'qualification', 'institution', 'address',
       'spouse', 'experience', 'province', 'district', 'constituency',
       'votes_cast', 'total_voters', 'education_category', 'latitude',
       'longitude', 'candidate_photo', 'party_symbol'],
      dtype='object')

In [186]:
candidate_info = ['gender','father','spouse','address','qualification','experience']

In [188]:
temp_df[candidate_info]

    gender            father spouse    address qualification experience
121      M  Ram Narayan Shah    NaN  Kathmandu           BTU        NaN

In [191]:
("Male" if temp_df[candidate_info]['gender'].values[0] == 'M' else "Female")

'Male'

In [213]:
df[df['candidate'] == 'Jyoti Yonjan']['spouse'] == ' '

3117    True
Name: spouse, dtype: bool