# Load data

In [1]:
import numpy as np 
import pandas as pd

In [2]:
parties = pd.read_csv(r"H:\DALearning\PythonCodes\PythonLearning\Z-Projects (DA)\Election-2082\2. data_wrangling\2.1 data_gathering\second_way\parties.csv")

In [3]:
constituencies = pd.read_csv(r"H:\DALearning\PythonCodes\PythonLearning\Z-Projects (DA)\Election-2082\2. data_wrangling\2.1 data_gathering\second_way\constituencies.csv")

In [4]:
candidates = pd.read_csv(r"H:\DALearning\PythonCodes\PythonLearning\Z-Projects (DA)\Election-2082\2. data_wrangling\2.1 data_gathering\second_way\candidates.csv")

## **Parties table**

In [5]:
parties.head()

,partyId,partyName,prVotes,voteShare
0,2528,राष्ट्रिय स्वतन्त्र पार्टी,5183493,47.8402
1,2583,नेपाली काँग्रेस,1759172,16.2360
2,2598,नेपाल कम्युनिष्ट पार्टी (एकीकृत मार्क्सवादी ले...,1455885,13.4368
3,2557,नेपाली कम्युनिष्ट पार्टी,811577,7.4903
4,2501,श्रम संस्कृति पार्टी,385902,3.5616

In [6]:
parties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   partyId    57 non-null     int64
 1   partyName  57 non-null     object
 2   prVotes    57 non-null     int64
 3   voteShare  57 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.9+ KB

## **Constituencies table**

In [7]:
constituencies.head()

,province,district,districtNp,code,name,nameNp,status,lastUpdated,votesCast,totalVoters
0,Koshi,Taplejung,ताप्लेजुङ,1-ताप्लेजुङ-1,Taplejung-1,ताप्लेजुङ क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,42897,90308
1,Koshi,Panchthar,पाँचथर,1-पाँचथर-1,Panchthar-1,पाँचथर क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,66921,143358
2,Koshi,Ilam,इलाम,1-इलाम-1,Ilam-1,इलाम क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,59391,112296
3,Koshi,Ilam,इलाम,1-इलाम-2,Ilam-2,इलाम क्षेत्र नं. 2,DECLARED,2026-06-30T21:28:05.771Z,63781,119475
4,Koshi,Jhapa,झापा,1-झापा-1,Jhapa-1,झापा क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,78291,130993

In [8]:
constituencies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   province     165 non-null    object
 1   district     165 non-null    object
 2   districtNp   165 non-null    object
 3   code         165 non-null    object
 4   name         165 non-null    object
 5   nameNp       165 non-null    object
 6   status       165 non-null    object
 7   lastUpdated  165 non-null    object
 8   votesCast    165 non-null    int64
 9   totalVoters  165 non-null    int64
dtypes: int64(2), object(8)
memory usage: 13.0+ KB

## **Candidates table**

In [28]:
candidates.head()

,candidateId,nameNp,name,partyName,partyId,votes,gender,isWinner,fatherName,qualification,institution,address,spouseName,experience,code,CandidateID,AGE_YR
0,339933,क्षितिज थेबे,Khitiz Thebe,नेपाल कम्युनिष्ट पार्टी (एकीकृत मार्क्सवादी ले...,2598,13962,M,True,भुपेन्द्र थेबे,स्नातक,TU,ताप्लेजुङ सिरीजङ्घा गाउँपालिका मादिबुङ,NaN,NaN,1-ताप्लेजुङ-1,339933,38
1,341131,गजेन्द्र प्रसाद तुम्याङ लिम्बु,Gajendra Prasad Tumyang Limbu,नेपाली काँग्रेस,2583,11711,M,False,Purna Bahadur Limbu,स्नातक,पाथीभरा वहुमुखी क्याम्पस,Taplejung,Radhika Lingden Tumyang,NaN,1-ताप्लेजुङ-1,341131,46
2,339610,खेल प्रसाद बुडाक्षेत्री,Khel Prasad Buda Chhetri,नेपाली कम्युनिष्ट पार्टी,2557,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,TU,ताप्लेजुङ सिरीजङ्घा गाउँपालिका चिचिहाङ्ग,कुमारी बुडाक्षेत्री,NaN,1-ताप्लेजुङ-1,339610,50
3,340005,सन्तोष राई,Santosh Rai,श्रम संस्कृति पार्टी,2501,5209,M,False,Bal Bahadur Rai,कक्षा ८,गणेश मा.वि. खेवाङ,Taplejung,Sita Rai,NaN,1-ताप्लेजुङ-1,340005,49
4,340459,बिरेन्द्र श्रेष्ठ,Birendra Shrestha,राष्ट्रिय स्वतन्त्र पार्टी,2528,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,युनिभर सिटी आर्मानिय,Taplejung,Manolak Wuphashree Shrestha,NaN,1-ताप्लेजुङ-1,340459,55

In [10]:
candidates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   candidateId    3406 non-null   int64
 1   nameNp         3406 non-null   object
 2   name           3406 non-null   object
 3   partyName      3406 non-null   object
 4   partyId        3406 non-null   object
 5   votes          3406 non-null   int64
 6   gender         3406 non-null   object
 7   isWinner       3406 non-null   bool
 8   fatherName     3405 non-null   object
 9   qualification  2762 non-null   object
 10  institution    1769 non-null   object
 11  address        3406 non-null   object
 12  spouseName     2595 non-null   object
 13  experience     1083 non-null   object
 14  code           3406 non-null   object
 15  CandidateID    3406 non-null   int64
 16  AGE_YR         3406 non-null   int64
dtypes: bool(1), int64(4), object(12)
memory usage: 429.2+ KB

# Merge tables

## **candidates** + **constituencies**

In [29]:
df = candidates.merge(constituencies, on='code')

In [30]:
df

,candidateId,nameNp_x,name_x,partyName,partyId,votes,gender,isWinner,fatherName,qualification,...,AGE_YR,province,district,districtNp,name_y,nameNp_y,status,lastUpdated,votesCast,totalVoters
0,339933,क्षितिज थेबे,Khitiz Thebe,नेपाल कम्युनिष्ट पार्टी (एकीकृत मार्क्सवादी ले...,2598,13962,M,True,भुपेन्द्र थेबे,स्नातक,...,38,Koshi,Taplejung,ताप्लेजुङ,Taplejung-1,ताप्लेजुङ क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,42897,90308
1,341131,गजेन्द्र प्रसाद तुम्याङ लिम्बु,Gajendra Prasad Tumyang Limbu,नेपाली काँग्रेस,2583,11711,M,False,Purna Bahadur Limbu,स्नातक,...,46,Koshi,Taplejung,ताप्लेजुङ,Taplejung-1,ताप्लेजुङ क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,42897,90308
2,339610,खेल प्रसाद बुडाक्षेत्री,Khel Prasad Buda Chhetri,नेपाली कम्युनिष्ट पार्टी,2557,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,...,50,Koshi,Taplejung,ताप्लेजुङ,Taplejung-1,ताप्लेजुङ क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,42897,90308
3,340005,सन्तोष राई,Santosh Rai,श्रम संस्कृति पार्टी,2501,5209,M,False,Bal Bahadur Rai,कक्षा ८,...,49,Koshi,Taplejung,ताप्लेजुङ,Taplejung-1,ताप्लेजुङ क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,42897,90308
4,340459,बिरेन्द्र श्रेष्ठ,Birendra Shrestha,राष्ट्रिय स्वतन्त्र पार्टी,2528,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,...,55,Koshi,Taplejung,ताप्लेजुङ,Taplejung-1,ताप्लेजुङ क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,42897,90308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3401,339584,सत्‍यनारायण श्रेष्ठ,Sat‍yanarayana Shreshth,राष्ट्रिय जनमोर्चा,2522,170,M,False,चित्रबहादुर श्रेष्ठ,आठ कक्षा उतिर्ण,...,62,Karnali,Rukum West,रुकुम (पश्चिम भाग),Rukum West-1,रुकुम (पश्चिम भाग) क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,59523,106650
3402,341508,नरेन्द्र के.सी,Narendra Ke.si,उज्यालो नेपाल पार्टी,2566,84,M,False,पुस्प्रसिंह के.सी,स्नातकोत्तर,...,48,Karnali,Rukum West,रुकुम (पश्चिम भाग),Rukum West-1,रुकुम (पश्चिम भाग) क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,59523,106650
3403,341627,शेर बहादुर के.सी.,Shera Bahadura Ke.si.,नेपाल कम्युनिष्ट पार्टी (संयुक्त),2601,54,M,False,दिलबहादुर के.सी.,प्रमाणपत्र तह,...,70,Karnali,Rukum West,रुकुम (पश्चिम भाग),Rukum West-1,रुकुम (पश्चिम भाग) क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,59523,106650
3404,341758,प्रेमा दमाई नेपाली,Prema Damaee Nepali,आम जनता पार्टी(एकल चुनाव चिन्ह),2581,45,F,False,धर्मे दमाई,आधारभुत तह,...,44,Karnali,Rukum West,रुकुम (पश्चिम भाग),Rukum West-1,रुकुम (पश्चिम भाग) क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,59523,106650
3405,340480,धन बहादुर वि.क.,Dhana Bahadura Vi.ka.,नेपाल मजदुर किसान पार्टी,2578,15,M,False,जसी कामी,प्रमाणपत्र तह,...,43,Karnali,Rukum West,रुकुम (पश्चिम भाग),Rukum West-1,रुकुम (पश्चिम भाग) क्षेत्र नं. 1,DECLARED,2026-06-30T21:28:05.771Z,59523,106650

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   candidateId    3406 non-null   int64
 1   nameNp_x       3406 non-null   object
 2   name_x         3406 non-null   object
 3   partyName      3406 non-null   object
 4   partyId        3406 non-null   object
 5   votes          3406 non-null   int64
 6   gender         3406 non-null   object
 7   isWinner       3406 non-null   bool
 8   fatherName     3405 non-null   object
 9   qualification  2762 non-null   object
 10  institution    1769 non-null   object
 11  address        3406 non-null   object
 12  spouseName     2595 non-null   object
 13  experience     1083 non-null   object
 14  code           3406 non-null   object
 15  CandidateID    3406 non-null   int64
 16  AGE_YR         3406 non-null   int64
 17  province       3406 non-null   object
 18  district       3406 non-null   object
 19  districtNp     3406 non-null   object
 20  name_y         3406 non-null   object
 21  nameNp_y       3406 non-null   object
 22  status         3406 non-null   object
 23  lastUpdated    3406 non-null   object
 24  votesCast      3406 non-null   int64
 25  totalVoters    3406 non-null   int64
dtypes: bool(1), int64(6), object(19)
memory usage: 668.7+ KB

# Feature selection

- candidateId
- name_x
- AGE_YR
- partyName
- partyId
- votes
- gender
- isWinner
- fatherName
- qualification
- institution
- address
- spouseName
- experience
- code
- province
- district
- name_y
- votesCast
- totalVoters

> Here, I selected the features that are most relevant for predicting whether a candidate is likely to win an election.

In [32]:
df.columns

Index(['candidateId', 'nameNp_x', 'name_x', 'partyName', 'partyId', 'votes',
       'gender', 'isWinner', 'fatherName', 'qualification', 'institution',
       'address', 'spouseName', 'experience', 'code', 'CandidateID', 'AGE_YR',
       'province', 'district', 'districtNp', 'name_y', 'nameNp_y', 'status',
       'lastUpdated', 'votesCast', 'totalVoters'],
      dtype='object')

In [33]:
selected_cols = [
    'candidateId',
    'name_x',
    'AGE_YR',
    'partyName',
    'partyId',
    'votes',
    'gender',
    'isWinner',
    'fatherName',
    'qualification',
    'institution',
    'address',
    'spouseName',
    'experience',
    'code',
    'province',
    'district',
    'name_y',
    'votesCast',
    'totalVoters'
    ]

In [34]:
df = df[selected_cols]
df

,candidateId,name_x,AGE_YR,partyName,partyId,votes,gender,isWinner,fatherName,qualification,institution,address,spouseName,experience,code,province,district,name_y,votesCast,totalVoters
0,339933,Khitiz Thebe,38,नेपाल कम्युनिष्ट पार्टी (एकीकृत मार्क्सवादी ले...,2598,13962,M,True,भुपेन्द्र थेबे,स्नातक,TU,ताप्लेजुङ सिरीजङ्घा गाउँपालिका मादिबुङ,NaN,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
1,341131,Gajendra Prasad Tumyang Limbu,46,नेपाली काँग्रेस,2583,11711,M,False,Purna Bahadur Limbu,स्नातक,पाथीभरा वहुमुखी क्याम्पस,Taplejung,Radhika Lingden Tumyang,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
2,339610,Khel Prasad Buda Chhetri,50,नेपाली कम्युनिष्ट पार्टी,2557,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,TU,ताप्लेजुङ सिरीजङ्घा गाउँपालिका चिचिहाङ्ग,कुमारी बुडाक्षेत्री,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
3,340005,Santosh Rai,49,श्रम संस्कृति पार्टी,2501,5209,M,False,Bal Bahadur Rai,कक्षा ८,गणेश मा.वि. खेवाङ,Taplejung,Sita Rai,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
4,340459,Birendra Shrestha,55,राष्ट्रिय स्वतन्त्र पार्टी,2528,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,युनिभर सिटी आर्मानिय,Taplejung,Manolak Wuphashree Shrestha,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3401,339584,Sat‍yanarayana Shreshth,62,राष्ट्रिय जनमोर्चा,2522,170,M,False,चित्रबहादुर श्रेष्ठ,आठ कक्षा उतिर्ण,श्री मा.वि. थवाङ्ग,रुकुम (पश्चिम भाग) मुसिकोट नगरपालिका खलंगा,शीतली माया श्रेष्ठ,NaN,6-रुकुम (पश्चिम भाग)-1,Karnali,Rukum West,Rukum West-1,59523,106650
3402,341508,Narendra Ke.si,48,उज्यालो नेपाल पार्टी,2566,84,M,False,पुस्प्रसिंह के.सी,स्नातकोत्तर,त्रि.वि.वि./ खुला बिश्वविद्यालय भारत,रुकुम (पश्चिम भाग) आठबिसकोट नगरपालिका फारुला,विणा शर्मा,राष्ट्रिय अन्तर्राष्ट्रिय गैरसरकारी संस्थामा २...,6-रुकुम (पश्चिम भाग)-1,Karnali,Rukum West,Rukum West-1,59523,106650
3403,341627,Shera Bahadura Ke.si.,70,नेपाल कम्युनिष्ट पार्टी (संयुक्त),2601,54,M,False,दिलबहादुर के.सी.,प्रमाणपत्र तह,NaN,रुकुम (पश्चिम भाग) चौरजहारी नगरपालिका देउरालटा...,"तुल्सीर पुष्पा,टेका के.सी.",शिक्षा सास्त्र संस्थान नेपालगञ्ज,6-रुकुम (पश्चिम भाग)-1,Karnali,Rukum West,Rukum West-1,59523,106650
3404,341758,Prema Damaee Nepali,44,आम जनता पार्टी(एकल चुनाव चिन्ह),2581,45,F,False,धर्मे दमाई,आधारभुत तह,जनजागृति मा.वि. साँख,रुकुम (पश्चिम भाग) मुसिकोट नगरपालिका सालघारी,दलवहादुर नेपाली,10 वर्ष राजनितकअनुभव,6-रुकुम (पश्चिम भाग)-1,Karnali,Rukum West,Rukum West-1,59523,106650
3405,340480,Dhana Bahadura Vi.ka.,43,नेपाल मजदुर किसान पार्टी,2578,15,M,False,जसी कामी,प्रमाणपत्र तह,त्रिभुवन विश्वविद्यालय,सुर्खेत पञ्चपुरी नगरपालिका च्युरीखेत,जानकी सुनार,ने.म.कि.पा.मा विगत २५ वर्षदेखि क्रियासिल,6-रुकुम (पश्चिम भाग)-1,Karnali,Rukum West,Rukum West-1,59523,106650

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   candidateId    3406 non-null   int64
 1   name_x         3406 non-null   object
 2   AGE_YR         3406 non-null   int64
 3   partyName      3406 non-null   object
 4   partyId        3406 non-null   object
 5   votes          3406 non-null   int64
 6   gender         3406 non-null   object
 7   isWinner       3406 non-null   bool
 8   fatherName     3405 non-null   object
 9   qualification  2762 non-null   object
 10  institution    1769 non-null   object
 11  address        3406 non-null   object
 12  spouseName     2595 non-null   object
 13  experience     1083 non-null   object
 14  code           3406 non-null   object
 15  province       3406 non-null   object
 16  district       3406 non-null   object
 17  name_y         3406 non-null   object
 18  votesCast      3406 non-null   int64
 19  totalVoters    3406 non-null   int64
dtypes: bool(1), int64(5), object(14)
memory usage: 509.0+ KB

# Data assessing

## **Manual assessment:**

### Quality issues

1. **name_x** 
    - candidate column is not recognisable   `accuracy`

2. **partyName**
    - party names in devanagari font    `consistency`

3. **qualification**
    - some values in devanagari font     `consistency`

4. **address**
    - some values in devanagari font     `consistency`

5. **name_y**
    - constituency column is not recognisable   `accuracy`

### Tidiness issues

- No structural issues

## **Programmatic assessment:**

### Quality issues

1. **partyId**
    - data type in text format   `validity`

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   candidateId    3406 non-null   int64
 1   name_x         3406 non-null   object
 2   AGE_YR         3406 non-null   int64
 3   partyName      3406 non-null   object
 4   partyId        3406 non-null   object
 5   votes          3406 non-null   int64
 6   gender         3406 non-null   object
 7   isWinner       3406 non-null   bool
 8   fatherName     3405 non-null   object
 9   qualification  2762 non-null   object
 10  institution    1769 non-null   object
 11  address        3406 non-null   object
 12  spouseName     2595 non-null   object
 13  experience     1083 non-null   object
 14  code           3406 non-null   object
 15  province       3406 non-null   object
 16  district       3406 non-null   object
 17  name_y         3406 non-null   object
 18  votesCast      3406 non-null   int64
 19  totalVoters    3406 non-null   int64
dtypes: bool(1), int64(5), object(14)
memory usage: 509.0+ KB

In [37]:
df.describe()

         candidateId       AGE_YR         votes      votesCast    totalVoters
count    3406.000000  3406.000000   3406.000000    3406.000000    3406.000000
mean   341043.324427    46.959777   3100.122431   67452.421903  117135.224897
std      1009.146462    11.276963   7806.744228   15801.515770   26983.488274
min    339300.000000    25.000000      0.000000    2878.000000    7000.000000
25%    340169.250000    39.000000     17.000000   59147.000000  105909.000000
50%    341039.500000    47.000000     87.000000   69184.000000  117917.000000
75%    341917.750000    55.000000    966.500000   78037.000000  134426.000000
max    342797.000000    88.000000  68348.000000  102338.000000  187939.000000

In [38]:
df.duplicated().sum()

np.int64(0)

- *Some cols like **fatherName**, **qualification**, **institution**, **spouseName**, **experience** have missing values which can't be filled.*

# Data cleaning

In [39]:
# make a copy first
df1 = df.copy()

## **Validity issues:**

### `partyId`

In [40]:
df1['partyId'].astype(int)

ValueError: invalid literal for int() with base 10: 'IND'

- *Since the column contains a mixture of numbers and text, it cannot be explicitly converted to the `int` data type.*

In [41]:
df1['partyId'].str.isdigit().sum()

np.int64(2263)

In [42]:
# 1. Convert 'IND' text to NaN safely
df1['partyId'] = pd.to_numeric(df1['partyId'], errors='coerce')

In [43]:
df1['partyId'].dtype

dtype('float64')

## **Accuracy issues:**

### `name_x` and `name_y`

In [44]:
df1.rename(columns={'name_x':'candidate', 'name_y':'constituency'}, inplace=True)

In [45]:
df1.head()

,candidateId,candidate,AGE_YR,partyName,partyId,votes,gender,isWinner,fatherName,qualification,institution,address,spouseName,experience,code,province,district,constituency,votesCast,totalVoters
0,339933,Khitiz Thebe,38,नेपाल कम्युनिष्ट पार्टी (एकीकृत मार्क्सवादी ले...,2598.0,13962,M,True,भुपेन्द्र थेबे,स्नातक,TU,ताप्लेजुङ सिरीजङ्घा गाउँपालिका मादिबुङ,NaN,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
1,341131,Gajendra Prasad Tumyang Limbu,46,नेपाली काँग्रेस,2583.0,11711,M,False,Purna Bahadur Limbu,स्नातक,पाथीभरा वहुमुखी क्याम्पस,Taplejung,Radhika Lingden Tumyang,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
2,339610,Khel Prasad Buda Chhetri,50,नेपाली कम्युनिष्ट पार्टी,2557.0,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,TU,ताप्लेजुङ सिरीजङ्घा गाउँपालिका चिचिहाङ्ग,कुमारी बुडाक्षेत्री,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
3,340005,Santosh Rai,49,श्रम संस्कृति पार्टी,2501.0,5209,M,False,Bal Bahadur Rai,कक्षा ८,गणेश मा.वि. खेवाङ,Taplejung,Sita Rai,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308
4,340459,Birendra Shrestha,55,राष्ट्रिय स्वतन्त्र पार्टी,2528.0,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,युनिभर सिटी आर्मानिय,Taplejung,Manolak Wuphashree Shrestha,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308

## **Consistency issues:**

### `partyName`

In [46]:
df1['partyName'].nunique()

66

In [48]:
df1['partyName'].unique()

array(['नेपाल कम्युनिष्ट पार्टी (एकीकृत मार्क्सवादी लेनिनवादी)',
       'नेपाली काँग्रेस', 'नेपाली कम्युनिष्ट पार्टी',
       'श्रम संस्कृति पार्टी', 'राष्ट्रिय स्वतन्त्र पार्टी',
       'उज्यालो नेपाल पार्टी', 'संघीय लोकतान्त्रिक राष्ट्रिय मञ्च',
       'राष्ट्रिय प्रजातन्त्र पार्टी',
       'नेपाल कम्युनिस्ट पार्टी (माओवादी)',
       'जनता समाजवादी पार्टी(एकल चुनाव चिन्ह)',
       'जनता समाजवादी पार्टी, नेपाल', 'मंगोल नेशनल अर्गनाइजेसन',
       'नेपाल जनमुक्ति पार्टी', 'राष्ट्रिय परिवर्तन पार्टी',
       'राष्ट्रिय मुक्ति पार्टी नेपाल(एकल चुनाव चिन्ह)',
       'प्रगतिशील लोकतान्त्रिक पार्टी', 'नेपाल मजदुर किसान पार्टी',
       'राष्ट्रिय जनमुक्ति पार्टी', 'स्वतन्त्र', 'नेपाल सद्भावना पार्टी',
       'जनमत पार्टी', 'नेपाल कम्युनिष्ट पार्टी (संयुक्त)',
       'नेशनल रिपब्लिक नेपाल',
       'नेपाल कम्युनिष्ट पार्टी मार्क्सवादी (पुष्पलाल)',
       'पिपुल फर्ष्ट पार्टी', 'राष्ट्रिय जनमोर्चा',
       'नेपाली जनश्रमदान संस्कृति पार्टी',
       'आम जनता पार्टी(एकल चुनाव चिन्ह)', 'मितेरी पार्टी नेपाल',
       'राष्ट्रिय उर्जाशील पार्टी, नेपाल', 'संयुक्त नागरिक पार्टी',
       'जय मातृभूमि पार्टी', 'राष्ट्र निर्माण दल नेपाल',
       'समावेशी समाजवादी पार्टी',
       'नागरिक उन्मुक्ति पार्टी, नेपाल(एकल चुनाव चिन्ह)',
       'सार्वभौम नागरिक पार्टी', 'राष्ट्रिय साझा पार्टी',
       'नेपाल लोकतान्त्रिक पार्टी', 'समावेशी समाजवादी पार्टी नेपाल',
       'नेपाल जनता पार्टी', 'नेपाली जनता दल',
       'नागरिक सर्वोच्चता पार्टी नेपाल(एकल चुनाव चिन्ह)',
       'स्वाभिमान पार्टी', 'नेपाल जनता संरक्षण पार्टी',
       'राष्ट्रिय एकता दल', 'जन अधिकार पार्टी',
       'नेपालका लागि नेपाली पार्टी', 'जनता लोकतान्त्रिक पार्टी, नेपाल',
       'नेपाल संघीय समाजवादी पार्टी(एकल चुनाव चिन्ह)',
       'बहुजन एकता पार्टी नेपाल(एकल चुनाव चिन्ह)', 'बहुजन शक्ति पार्टी',
       'इतिहासिक जनता पार्टी', 'जनादेश पार्टी नेपाल(एकल चुनाव चिन्ह)',
       'राष्ट्रिय जनता पार्टी नेपाल', 'राष्ट्रिय मुक्ति आन्दोलन, नेपाल',
       'गतिशील लोकतान्त्रिक पार्टी', 'युनाईटेड नेपाल डिमोक्रयाटीक पार्टी',
       'प्रजातान्त्रिक पार्टी नेपाल', 'नेपाल जनसेवा पार्टी',
       'त्रिमूल नेपाल',
       'नेपाल कम्युनिष्ट पार्टी (माक्र्सवादी)(एकल चुनाव चिन्ह)',
       ' राष्ट्रिय नागरिक पार्टी', 'नेपाल मानवतावादी पार्टी',
       'नेपाल मातृभूमि पार्टी', 'गान्धीवादी पार्टी नेपाल',
       'राष्ट्रिय जनमत पार्टी'], dtype=object)

In [49]:
party_translate = {
    'नेपाल कम्युनिष्ट पार्टी (एकीकृत मार्क्सवादी लेनिनवादी)': 'Nepal Communist Party (Ekikrit Marxbadi Leninbadi)',
    'नेपाली काँग्रेस': 'Nepali Congress',
    'नेपाली कम्युनिष्ट पार्टी': 'Nepali Communist Party',
    'श्रम संस्कृति पार्टी': 'Shram Sanskriti Party',
    'राष्ट्रिय स्वतन्त्र पार्टी': 'Rastriya Swatantra Party',
    'उज्यालो नेपाल पार्टी': 'Ujyalo Nepal Party',
    'संघीय लोकतान्त्रिक राष्ट्रिय मञ्च': 'Sanghiya Loktantrik Rastriya Manch',
    'राष्ट्रिय प्रजातन्त्र पार्टी': 'Rastriya Prajatantra Party',
    'नेपाल कम्युनिस्ट पार्टी (माओवादी)': 'Nepal Communist Party (Maoist)',
    'जनता समाजवादी पार्टी(एकल चुनाव चिन्ह)': 'Janata Samajbadi Party (Ekal Chunab Chinha)',
    'जनता समाजवादी पार्टी, नेपाल': 'Janata Samajbadi Party, Nepal',
    'मंगोल नेशनल अर्गनाइजेसन': 'Mongol National Organization',
    'नेपाल जनमुक्ति पार्टी': 'Nepal Janamukti Party',
    'राष्ट्रिय परिवर्तन पार्टी': 'Rastriya Paribartan Party',
    'राष्ट्रिय मुक्ति पार्टी नेपाल(एकल चुनाव चिन्ह)': 'Rastriya Mukti Party Nepal (Ekal Chunab Chinha)',
    'प्रगतिशील लोकतान्त्रिक पार्टी': 'Pragatishil Loktantrik Party',
    'नेपाल मजदुर किसान पार्टी': 'Nepal Majdur Kisan Party',
    'राष्ट्रिय जनमुक्ति पार्टी': 'Rastriya Janamukti Party',
    'स्वतन्त्र': 'Swatantra',
    'नेपाल सद्भावना पार्टी': 'Nepal Sadbhawana Party',
    'जनमत पार्टी': 'Janamat Party',
    'नेपाल कम्युनिष्ट पार्टी (संयुक्त)': 'Nepal Communist Party (Sanyukta)',
    'नेशनल रिपब्लिक नेपाल': 'National Republic Nepal',
    'नेपाल कम्युनिष्ट पार्टी मार्क्सवादी (पुष्पलाल)': 'Nepal Communist Party Marxbadi (Pushpalal)',
    'पिपुल फर्ष्ट पार्टी': 'People First Party',
    'राष्ट्रिय जनमोर्चा': 'Rastriya Janamorcha',
    'नेपाली जनश्रमदान संस्कृति पार्टी': 'Nepali Janashramdan Sanskriti Party',
    'आम जनता पार्टी(एकल चुनाव चिन्ह)': 'Aam Janata Party (Ekal Chunab Chinha)',
    'मितेरी पार्टी नेपाल': 'Miteri Party Nepal',
    'राष्ट्रिय उर्जाशील पार्टी, नेपाल': 'Rastriya Urjashil Party, Nepal',
    'संयुक्त नागरिक पार्टी': 'Sanyukta Nagarik Party',
    'जय मातृभूमि पार्टी': 'Jaya Matribhumi Party',
    'राष्ट्र निर्माण दल नेपाल': 'Rashtra Nirman Dal Nepal',
    'समावेशी समाजवादी पार्टी': 'Samabeshi Samajbadi Party',
    'नागरिक उन्मुक्ति पार्टी, नेपाल(एकल चुनाव चिन्ह)': 'Nagarik Unmukti Party, Nepal (Ekal Chunab Chinha)',
    'सार्वभौम नागरिक पार्टी': 'Sarbabhaum Nagarik Party',
    'राष्ट्रिय साझा पार्टी': 'Rastriya Sajha Party',
    'नेपाल लोकतान्त्रिक पार्टी': 'Nepal Loktantrik Party',
    'समावेशी समाजवादी पार्टी नेपाल': 'Samabeshi Samajbadi Party Nepal',
    'नेपाल जनता पार्टी': 'Nepal Janata Party',
    'नेपाली जनता दल': 'Nepali Janata Dal',
    'नागरिक सर्वोच्चता पार्टी नेपाल(एकल चुनाव चिन्ह)': 'Nagarik Sarbochchata Party Nepal (Ekal Chunab Chinha)',
    'स्वाभिमान पार्टी': 'Swabhiman Party',
    'नेपाल जनता संरक्षण पार्टी': 'Nepal Janata Sanrakshan Party',
    'राष्ट्रिय एकता दल': 'Rastriya Ekata Dal',
    'जन अधिकार पार्टी': 'Jan Adhikar Party',
    'नेपालका लागि नेपाली पार्टी': 'Nepalka Lagi Nepali Party',
    'जनता लोकतान्त्रिक पार्टी, नेपाल': 'Janata Loktantrik Party, Nepal',
    'नेपाल संघीय समाजवादी पार्टी(एकल चुनाव चिन्ह)': 'Nepal Sanghiya Samajbadi Party (Ekal Chunab Chinha)',
    'बहुजन एकता पार्टी नेपाल(एकल चुनाव चिन्ह)': 'Bahujan Ekata Party Nepal (Ekal Chunab Chinha)',
    'बहुजन शक्ति पार्टी': 'Bahujan Shakti Party',
    'इतिहासिक जनता पार्टी': 'Itihasik Janata Party',
    'जनादेश पार्टी नेपाल(एकल चुनाव चिन्ह)': 'Janadesh Party Nepal (Ekal Chunab Chinha)',
    'राष्ट्रिय जनता पार्टी नेपाल': 'Rastriya Janata Party Nepal',
    'राष्ट्रिय मुक्ति आन्दोलन, नेपाल': 'Rastriya Mukti Andolan, Nepal',
    'गतिशील लोकतान्त्रिक पार्टी': 'Gatishil Loktantrik Party',
    'युनाईटेड नेपाल डिमोक्रयाटीक पार्टी': 'United Nepal Democratic Party',
    'प्रजातान्त्रिक पार्टी नेपाल': 'Prajatantrik Party Nepal',
    'नेपाल जनसेवा पार्टी': 'Nepal Janasewa Party',
    'त्रिमूल नेपाल': 'Trimul Nepal',
    'नेपाल कम्युनिष्ट पार्टी (माक्र्सवादी)(एकल चुनाव चिन्ह)': 'Nepal Communist Party (Marxbadi) (Ekal Chunab Chinha)',
    ' राष्ट्रिय नागरिक पार्टी': 'Rastriya Nagarik Party',
    'नेपाल मानवतावादी पार्टी': 'Nepal Manabatabadi Party',
    'नेपाल मातृभूमि पार्टी': 'Nepal Matribhumi Party',
    'गान्धीवादी पार्टी नेपाल': 'Gandhiwadi Party Nepal',
    'राष्ट्रिय जनमत पार्टी': 'Rastriya Janamat Party'
}

In [50]:
# mapping dictionary
df1['partyName'] = df1['partyName'].map(party_translate)

In [51]:
df1['partyName'].value_counts()

partyName
Swatantra                                                1143
Nepali Congress                                           165
Nepal Communist Party (Ekikrit Marxbadi Leninbadi)        164
Nepali Communist Party                                    164
Rastriya Swatantra Party                                  164
                                                         ...
Rastriya Janata Party Nepal                                 1
Rastriya Nagarik Party                                      1
Nepal Communist Party (Marxbadi) (Ekal Chunab Chinha)       1
Nepal Matribhumi Party                                      1
Gandhiwadi Party Nepal                                      1
Name: count, Length: 66, dtype: int64

- *The party names converted into **Nepali Roman (romanized Nepali)** while preserving the original pronunciation as closely as possible.*

### `qualification`

In [52]:
df1['qualification'].nunique()

762

In [ ]:
# np.save('education.npy', df1['qualification'].unique())     # export all unique text into numpy array

In [53]:
education_category_mapping = {
    "स्नातक": "Bachelor's Degree",
    "I.s.c": "Higher Secondary / Intermediate (10+2 / PCL)",
    "कक्षा ८": "Basic Education (Up to Grade 8)",
    "ईन्जिनेरिङ ग्राजुएड": "Bachelor's Degree",
    "SLC": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "SEE": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "आई.ए.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एस.एल.सी": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एम.ए.": "Master's Degree",
    "कक्षा १०": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "साक्षर": "Literate / Non-Formal",
    "स्नात्तकोतर व्यवस्थापन": "Master's Degree",
    "I.A": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आ.ए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "+12": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आई .कम": "Higher Secondary / Intermediate (10+2 / PCL)",
    "बि.ए": "Bachelor's Degree",
    "सामान्य": "Literate / Non-Formal",
    "12+": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नातकोत्तर": "Master's Degree",
    "slc": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "कक्षा 12": "Higher Secondary / Intermediate (10+2 / PCL)",
    "SLC ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "कक्षा 10 पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "+ 2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "साधारण": "Literate / Non-Formal",
    "SLC पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "+SLC (पूर्व मध्‍यमा)": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "आई कम ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "प्रविणता प्रमाण पत्र": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नातक तह": "Bachelor's Degree",
    "वि ए": "Bachelor's Degree",
    "एम ए एमसीजे विद्यावारिधिरत": "Doctorate / PhD",
    "+2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "विद्यावारिधी देल्लि विश्वविद्यालय 2007": "Doctorate / PhD",
    "माध्यामिक तह": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "बि ए ": "Bachelor's Degree",
    "कक्षा १२": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एम ए अर्थशास्त्र / एम वि एस फाइनान्स": "Master's Degree",
    "स्‍नात्तकोतर": "Master's Degree",
    "स्‍नातक": "Bachelor's Degree",
    "डिप्लोमा": "Diploma / Certificate Level",
    "प्रविणता प्रमाण पत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "BA": "Bachelor's Degree",
    "आइ. ए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आई एड": "Higher Secondary / Intermediate (10+2 / PCL)",
    "‌+2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आइ ए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्‍नातक तह": "Bachelor's Degree",
    "एम ए राजनीति शास्त्र": "Master's Degree",
    "एम ए": "Master's Degree",
    "एस एल सि": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस एल सी (अन्डर)": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "इन्जिनियर": "Bachelor's Degree",
    "सामान्य लेखपढ": "Literate / Non-Formal",
    "एस एल सी": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस एल सी पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "प्लस टु": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एम एड": "Master's Degree",
    "BTU": "Bachelor's Degree",
    "10+2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "BBS": "Bachelor's Degree",
    "bachelor": "Bachelor's Degree",
    "स्नात्कोत्तर": "Master's Degree",
    "आचार्य": "Master's Degree",
    "बिद्यावारीधि": "Doctorate / PhD",
    "कक्षा ७ उत्तीर्ण": "Basic Education (Up to Grade 8)",
    "एम.ए": "Master's Degree",
    "बि.एड": "Bachelor's Degree",
    "एम.एड.": "Master's Degree",
    "आई.ए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "साधारण लेखपढ": "Literate / Non-Formal",
    "एम. एड": "Master's Degree",
    "अन्डर एस.एल.सी.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "SLC/CMA": "Diploma / Certificate Level",
    "प्राथमिक तह": "Basic Education (Up to Grade 8)",
    "९ कक्षा": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एम.ए. राजनौतिक शास्त्र": "Master's Degree",
    "एल.एल.बि": "Bachelor's Degree",
    "बि.एड. एम.ए समाज शास्त्र": "Master's Degree",
    "+2 pass": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एस.एल.सि": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "  एस एल सी": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "आई.एड.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एस.एल.सि.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "वि.एड. डब्लु": "Bachelor's Degree",
    "आई.एड": "Higher Secondary / Intermediate (10+2 / PCL)",
    "+२": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एल.एल.सी": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "व्याचुलर डिग्री": "Bachelor's Degree",
    "साधरण लेखपढ": "Literate / Non-Formal",
    "एस.एल.सी.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "प्रमाण पत्र उतीर्ण": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एल.एल.सि.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "१२": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एम.ए, एम.फिल(संविधान)": "M.Phil",
    "एम.ए.ग्रामिण विकाश": "Master's Degree",
    "प्रमाण पत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "दशौं कक्षा उत्तीर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "स्‍नात्तकोत्तर": "Master's Degree",
    "Bachelor of Medicine ": "Bachelor's Degree",
    "एम ए बि एड": "Master's Degree",
    "विधावारिधि": "Doctorate / PhD",
    "आई कम": "Higher Secondary / Intermediate (10+2 / PCL)",
    "M.A": "Master's Degree",
    "स्‍नातक ": "Bachelor's Degree",
    "एम ए, विड": "Master's Degree",
    "वि ए स्नातक एम ए ": "Master's Degree",
    "वि वि एस": "Bachelor's Degree",
    "१२ कक्षा": "Higher Secondary / Intermediate (10+2 / PCL)",
    " ‌+2 ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "प्रविणता प्रमाणपत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "वि ए स्नातक ": "Bachelor's Degree",
    " +2 ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "प्राथमिक तह ": "Basic Education (Up to Grade 8)",
    "एस.एल.सि.पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "वि.सए.सि.": "Bachelor's Degree",
    "एस.एल.सि. पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस.एस.सि.पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "प्रविणता प्रमाणपत्र ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "ऐस.एल.सि.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "MBA": "Master's Degree",
    "MS/MD स्नातकोत्तर": "Master's Degree",
    "10": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस.एस.सी. ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "स्‍नातकोत्तर": "Master's Degree",
    "एस.एस.सी. पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एम.ए./एल.एल.वि.": "Master's Degree",
    "उच्च शिक्षा": "Higher Secondary / Intermediate (10+2 / PCL)",
    "दश कक्षा": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस.एस.सी.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "प्रमाणपत्र तह उर्तिण": "Higher Secondary / Intermediate (10+2 / PCL)",
    "शिक्षित": "Literate / Non-Formal",
    "दश कक्षा पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "पि.एच.डि.": "Doctorate / PhD",
    "डिप्लोमा इन सिभिल इन्जिनियरिङ्ग": "Diploma / Certificate Level",
    "स्नाकोत्तर ": "Master's Degree",
    "एस. एल. सी.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "व्याचलर": "Bachelor's Degree",
    "बि.कम.": "Bachelor's Degree",
    "वि.एड.": "Bachelor's Degree",
    "स्नातक तह ": "Bachelor's Degree",
    "आठ पास": "Basic Education (Up to Grade 8)",
    "8 पास": "Basic Education (Up to Grade 8)",
    "प्रवेशिका": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एम.वि.एस.": "Master's Degree",
    "स्‍नाकोत्तर": "Master's Degree",
    "स्तानक मेकानिकल इन्जिनियरिङ्ग": "Bachelor's Degree",
    "स्नातोकत्तर(राजनैतिक शास्त्र)": "Master's Degree",
    "कक्षा १२ पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "+2 पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "कक्षा ५ पास": "Basic Education (Up to Grade 8)",
    "+२ पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "कक्षा ८ पास": "Basic Education (Up to Grade 8)",
    "lab Assitant": "Diploma / Certificate Level",
    "प्रमाणपत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "कक्षा ९ पास ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "12 पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "निरक्षर": "Illiterate",
    "विविएस": "Bachelor's Degree",
    "पिएच डि": "Doctorate / PhD",
    "साक्षरता": "Literate / Non-Formal",
    "एम‍.ए. (स्नातकोत्तर)": "Master's Degree",
    "माध्यमिक तह": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एम. ए.": "Master's Degree",
    "ज्योतिषशास्त्र विद्यावारिधी": "Doctorate / PhD",
    "आइ. ए.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "१०+२": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आइ एड": "Higher Secondary / Intermediate (10+2 / PCL)",
    "८ कक्षा पास": "Basic Education (Up to Grade 8)",
    "BL": "Bachelor's Degree",
    "मा.व.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "१२ पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "पि.एच.डी.": "Doctorate / PhD",
    "B.Ed.": "Bachelor's Degree",
    "दश पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "Bachelor": "Bachelor's Degree",
    "P.hd": "Doctorate / PhD",
    "Master": "Master's Degree",
    "ma": "Master's Degree",
    "बि.ई": "Bachelor's Degree",
    "H.A": "Diploma / Certificate Level",
    "एल एल सी": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "I.sc Forestory": "Higher Secondary / Intermediate (10+2 / PCL)",
    "विद्यावारिधि (पि.एच.डि)": "Doctorate / PhD",
    "स्नातक ": "Bachelor's Degree",
    "एम. ई.": "Master's Degree",
    "वि.एड": "Bachelor's Degree",
    "B.COM": "Bachelor's Degree",
    "अनपढ": "Illiterate",
    "ISC": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नातक तह BA": "Bachelor's Degree",
    "पल्स टु पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "प्रविणता प्रमाणपत्र": "Higher Secondary / Intermediate (10+2 / PCL)",
    "पल्स टु": "Higher Secondary / Intermediate (10+2 / PCL)",
    "SEE PASS ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "SLC PASS": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस.एल.सी ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "आई एल": "Higher Secondary / Intermediate (10+2 / PCL)",
    "प्रविणता तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "MBBS": "Bachelor's Degree",
    "7": "Basic Education (Up to Grade 8)",
    "8": "Basic Education (Up to Grade 8)",
    "B.A. JMC": "Bachelor's Degree",
    "BE CIVIL": "Bachelor's Degree",
    "B.A.": "Bachelor's Degree",
    "S.L.C": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "प्रविन्ता प्रमाण  पत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एम.एड": "Master's Degree",
    "छैन": "Illiterate",
    "बिएड": "Bachelor's Degree",
    "प्रविन्ता प्रमाण तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "M. FIL": "M.Phil",
    "I.Com": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एम वि.वि.एस": "Bachelor's Degree",
    "मास्टर डिग्री": "Master's Degree",
    "M.D.": "Master's Degree",
    "M.Sc. M.A": "Master's Degree",
    "sLC": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "नभएको": "Illiterate",
    "B.A": "Bachelor's Degree",
    " एम.ए.": "Master's Degree",
    "९ कक्षा पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "BBs": "Bachelor's Degree",
    "‌‌‍‌+2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "Inter": "Higher Secondary / Intermediate (10+2 / PCL)",
    "८ कक्षा": "Basic Education (Up to Grade 8)",
    "B.ed": "Bachelor's Degree",
    "inter": "Higher Secondary / Intermediate (10+2 / PCL)",
    "HA": "Diploma / Certificate Level",
    "मास्तर डिग्री": "Master's Degree",
    "सिभिल ईन्जीनियर": "Bachelor's Degree",
    "पि.एच.डी": "Doctorate / PhD",
    "स्‍नातक कानुन": "Bachelor's Degree",
    "९ पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एल.एल.बि.": "Bachelor's Degree",
    "एम.पि.ए.": "Master's Degree",
    "s.l.c": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "M.DE": "Master's Degree",
    "बि.ए.": "Bachelor's Degree",
    "१० कक्षा पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "sLc": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "under slc": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "साधारण ": "Literate / Non-Formal",
    "Under SLC": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "Ph.D": "Doctorate / PhD",
    "स्नाकोत्तर": "Master's Degree",
    "M.A.": "Master's Degree",
    "MAA-Phd M.Ed": "Doctorate / PhD",
    "llm": "Master's Degree",
    "मस्टर इन ट्रसपेटेसन सिटम ": "Master's Degree",
    "आ ए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एस ल सी": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एम ए/ बी এল": "Master's Degree",
    "बि. ए.ल ल बी": "Bachelor's Degree",
    "पी एच डी": "Doctorate / PhD",
    "isc": "Higher Secondary / Intermediate (10+2 / PCL)",
    "bbs": "Bachelor's Degree",
    "डिप्लोमा इन्जिनियरिङ्ग": "Diploma / Certificate Level",
    "आइ ऐड": "Higher Secondary / Intermediate (10+2 / PCL)",
    "BE": "Bachelor's Degree",
    "Y": "Unspecified / Others",
    "आइ ऐ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "+ २ पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आइ कम": "Higher Secondary / Intermediate (10+2 / PCL)",
    "८ पास": "Basic Education (Up to Grade 8)",
    "अनौपचारीक लेखपढ": "Literate / Non-Formal",
    "प्राथमिक परिक्षा पास": "Basic Education (Up to Grade 8)",
    "कक्षा ९": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "10 + 2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "सधारण लेखपढ": "Literate / Non-Formal",
    "ब्याचलर इक्ट्रिक": "Bachelor's Degree",
    "PHD ": "Doctorate / PhD",
    "B.Tech": "Bachelor's Degree",
    "B A": "Bachelor's Degree",
    "अ हे व": "Diploma / Certificate Level",
    "कक्षा 10": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "Master in political Science": "Master's Degree",
    "MA poltical science": "Master's Degree",
    "Bachelor in sociology": "Bachelor's Degree",
    "Bachelor in computer Science": "Bachelor's Degree",
    "एम टेक (इनजीनियरिङ्ग)": "Master's Degree",
    "I.SC": "Higher Secondary / Intermediate (10+2 / PCL)",
    "B.SC. Honours": "Bachelor's Degree",
    "Doctor": "Doctorate / PhD",
    "B.com": "Bachelor's Degree",
    "Diploma in civil Engineer": "Diploma / Certificate Level",
    "P.Hd.": "Doctorate / PhD",
    "B.B.S": "Bachelor's Degree",
    "Master in sociology": "Master's Degree",
    "Diploma in Civil Engineer": "Diploma / Certificate Level",
    "MCA": "Master's Degree",
    "I sc": "Higher Secondary / Intermediate (10+2 / PCL)",
    "MBS": "Master's Degree",
    "समान्य लेखपढ": "Literate / Non-Formal",
    "Bcom": "Bachelor's Degree",
    "B.Sc.": "Bachelor's Degree",
    "B.E.": "Bachelor's Degree",
    "I.Sc.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एस.इ.इ.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "इन्जिनियरीङ्ग": "Bachelor's Degree",
    "S.L.C.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "स्नातकोत्तर तह व्यवस्थान र कानूनमा स्नातक": "Master's Degree",
    "विद्यावारिधी": "Doctorate / PhD",
    "n": "Unspecified / Others",
    "सााधारण लेखपेढ": "Literate / Non-Formal",
    "slc pass": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "  साधारण लेखपढ": "Literate / Non-Formal",
    "  SLC": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस एल सि पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "मास्टर्स": "Master's Degree",
    "वि.ए.(स्नातक)": "Bachelor's Degree",
    "स्नातकोत्तरोपाधि": "Master's Degree",
    "8 कक्षा ": "Basic Education (Up to Grade 8)",
    "सधारण": "Literate / Non-Formal",
    "BALLB": "Bachelor's Degree",
    "8 कक्षा पास": "Basic Education (Up to Grade 8)",
    "8 कक्षा सम्म": "Basic Education (Up to Grade 8)",
    "कक्षा 8 सम्म": "Basic Education (Up to Grade 8)",
    "ईन्जिनियर": "Bachelor's Degree",
    "आई.ए.सी.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "वि.वि.ए.": "Bachelor's Degree",
    "वि.कम.": "Bachelor's Degree",
    "बिए.एल.एल.बी.": "Bachelor's Degree",
    "M.D. Medicine": "Master's Degree",
    "आइ एसी": "Higher Secondary / Intermediate (10+2 / PCL)",
    "+2 डिप्लोमा सिभिल": "Higher Secondary / Intermediate (10+2 / PCL)",
    "‌‌+2 Science": "Higher Secondary / Intermediate (10+2 / PCL)",
    "10‌‌+2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "कक्षा ७ उतिर्ण": "Basic Education (Up to Grade 8)",
    "आधारभुत तह": "Basic Education (Up to Grade 8)",
    "वि.ए.": "Bachelor's Degree",
    "‌‌+2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "प्रविणता ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "I.SC.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "साधरण": "Literate / Non-Formal",
    "i.com.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "s.l.c.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "कक्षा १० ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "+12 Science ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "११": "Higher Secondary / Intermediate (10+2 / PCL)",
    "साक्षर ": "Literate / Non-Formal",
    "१०+२ पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एस.एल.सी. उतिर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एम.बि.बि.एस": "Bachelor's Degree",
    "स्‍नातक (बि.ई)": "Bachelor's Degree",
    "एस. एल.सी. नेपाल": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "डिप्लोमा सिभिल ईन्जिनियर": "Diploma / Certificate Level",
    "एस. एल.सी.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "राजनितिक शास्त्रमा  स्नातोक्तर (एल.एल.बी.)": "Master's Degree",
    "प्रवोनता प्रमाण पत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "५": "Basic Education (Up to Grade 8)",
    "Diploma in Pharmachy": "Diploma / Certificate Level",
    "आठ कक्षा पास मात्र": "Basic Education (Up to Grade 8)",
    "५ पास": "Basic Education (Up to Grade 8)",
    "समान्य": "Literate / Non-Formal",
    "B.E. / M.A.": "Master's Degree",
    "एस एल सी ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "वैचलर": "Bachelor's Degree",
    "आय एस सी ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आधारभुत शिक्षा": "Basic Education (Up to Grade 8)",
    "एम फिल / पिएचडी अध्ययनरत": "Doctorate / PhD",
    "मास्टर": "Master's Degree",
    "+२ ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "सनातक": "Bachelor's Degree",
    "p.hd.": "Doctorate / PhD",
    "‍B.B.S.": "Bachelor's Degree",
    "एम.ए राजनितिशास्त्र ": "Master's Degree",
    "माष्टर डिग्री ": "Master's Degree",
    "एमएड": "Master's Degree",
    "बी.एड": "Bachelor's Degree",
    "s.L.C.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "नर्सिङ": "Diploma / Certificate Level",
    "MA/BL": "Master's Degree",
    "HSEB": "Higher Secondary / Intermediate (10+2 / PCL)",
    "10 कक्षा": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "master": "Master's Degree",
    "MS": "Master's Degree",
    "कक्षा १० पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "दिक्षीत ": "Bachelor's Degree",
    "स्नातक(व्यवस्थापन)": "Bachelor's Degree",
    "ISC/AHM": "Diploma / Certificate Level",
    "T.S.L.C": "Diploma / Certificate Level",
    "बिध्यावारिधी": "Doctorate / PhD",
    "आठ कक्षा": "Basic Education (Up to Grade 8)",
    "प्लस टु पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "slc पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "स्नाकोत्तर तह": "Master's Degree",
    "उच्च मा.वि.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "MSC/BE Civil": "Master's Degree",
    "M Pharmacy": "Master's Degree",
    "DR. MA": "Master's Degree",
    "विएड": "Bachelor's Degree",
    "PHD": "Doctorate / PhD",
    "एसएलसी": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "व्याचलर कर्मश": "Bachelor's Degree",
    "स्‍नातकोत्तर ": "Master's Degree",
    "एम.एड. (बि.कम.)": "Master's Degree",
    "एस.एल.सी.+ प्रवीणता प्रमाणपत्र सम्म अध्ययन ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "वि.वि.ए. ": "Bachelor's Degree",
    "LLM, CA, MBA, MA (ECO)": "Master's Degree",
    "आठ पास ": "Basic Education (Up to Grade 8)",
    "एम.ए./वि.एल.": "Master's Degree",
    "दश कक्षा ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एम.वि.वि.एस": "Bachelor's Degree",
    "जनरल मेडिसिन /फार्मेसी": "Diploma / Certificate Level",
    "सामान्य ": "Literate / Non-Formal",
    "MBA, ME": "Master's Degree",
    "विद्यावारिधि": "Doctorate / PhD",
    "लेखपढ": "Literate / Non-Formal",
    "+२ उत्तीर्ण": "Higher Secondary / Intermediate (10+2 / PCL)",
    "१० पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "इन्जिनियरिङ्गमा स्नातक": "Bachelor's Degree",
    "७ पास": "Basic Education (Up to Grade 8)",
    "स्नाकोत्तर (LL.M., MPA)": "Master's Degree",
    "आई.कम.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "MA., M.Sc.": "Master's Degree",
    "स्नातक (आर्युवेद)": "Bachelor's Degree",
    "एम्.फिल. (अन्तर्राष्ट्रिय सम्बन्ध)": "M.Phil",
    "प्रविणता पत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "MBBS, Master": "Master's Degree",
    "12 pass": "Higher Secondary / Intermediate (10+2 / PCL)",
    "educated": "Literate / Non-Formal",
    "Bsc. Ag.": "Bachelor's Degree",
    "IA": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नताकोत्तर": "Master's Degree",
    "स्नातक (बि.कम)": "Bachelor's Degree",
    "स्नातक अध्ययनरत": "Bachelor's Degree",
    "bachelor running": "Bachelor's Degree",
    "स्नातक वाणिज्य शास्त्र": "Bachelor's Degree",
    "कक्षा दस पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "M. PHIL Economics, BBA LLB": "M.Phil",
    "+ २": "Higher Secondary / Intermediate (10+2 / PCL)",
    "BA LLB": "Bachelor's Degree",
    "Diploma in Electronics Engineering": "Diploma / Certificate Level",
    "१०": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "बी.एल": "Bachelor's Degree",
    "Master Degree": "Master's Degree",
    "PCL": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आधारभूत": "Basic Education (Up to Grade 8)",
    "Intermediate in commerce": "Higher Secondary / Intermediate (10+2 / PCL)",
    "I. Com": "Higher Secondary / Intermediate (10+2 / PCL)",
    "Phd Doctor": "Doctorate / PhD",
    "BA LLB ": "Bachelor's Degree",
    "एम.बि.ए": "Master's Degree",
    "एम.बि.एस. अध्ययन": "Master's Degree",
    "स्नातकोत्तर(एम.पि.ए.)": "Master's Degree",
    "एल एल एम/ एम ए": "Master's Degree",
    "10+2 ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "10 कक्षा उर्तीण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस.एल.सी. उत्तीर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "आई.ए. उत्तीर्ण": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नातकतह": "Bachelor's Degree",
    "मा.वि.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "मा. वि.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "कक्षा 9": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "7 pass ": "Basic Education (Up to Grade 8)",
    "7 कक्षा ": "Basic Education (Up to Grade 8)",
    "८": "Basic Education (Up to Grade 8)",
    "आई.कम": "Higher Secondary / Intermediate (10+2 / PCL)",
    "12": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एस.एस.सि.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "masters": "Master's Degree",
    "Masters": "Master's Degree",
    "bachelor in engineering ": "Bachelor's Degree",
    "Mphil": "M.Phil",
    "एम बि बि एस": "Bachelor's Degree",
    "स्नातकोत्तर तह": "Master's Degree",
    "B.sc MBBS, MBA": "Master's Degree",
    "M.A political science/PHD sclor": "Doctorate / PhD",
    "8 pass": "Basic Education (Up to Grade 8)",
    "वि इ": "Bachelor's Degree",
    "M phill": "M.Phil",
    "simple": "Literate / Non-Formal",
    "bachlor": "Bachelor's Degree",
    "I A": "Higher Secondary / Intermediate (10+2 / PCL)",
    "ABA कम्प्युटर इन्जिनियरिङ ": "Bachelor's Degree",
    "MA": "Master's Degree",
    "I L": "Higher Secondary / Intermediate (10+2 / PCL)",
    "Engineer": "Bachelor's Degree",
    "10 pass": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "Phd. in Electrical Engineering": "Doctorate / PhD",
    "Computer Engineering": "Bachelor's Degree",
    "स्नातकोतर": "Master's Degree",
    "माष्टर्स डिग्री (एम.बि.एस., एम.ए, LLB)": "Master's Degree",
    "आई ए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्‍नातक (बि.डि.एस)": "Bachelor's Degree",
    "६ कक्षा अध्ययन": "Basic Education (Up to Grade 8)",
    "१०  पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "इन्टरमेडियट": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्‍नातक अध्ययन": "Bachelor's Degree",
    "एम.ए. राजनितिक सास्त्र बि.एड": "Master's Degree",
    "B.ED": "Bachelor's Degree",
    "स्‍नातक ताह": "Bachelor's Degree",
    "डिल्लोमा इन्जनियरिङ्ग": "Diploma / Certificate Level",
    "इन्टरमिडिएट": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एम.बि.बि.एस.": "Bachelor's Degree",
    "स्‍नात्तक": "Bachelor's Degree",
    "Proficiency Certificate Level (PCL)": "Higher Secondary / Intermediate (10+2 / PCL)",
    "BSC in Computing And Information Techn": "Bachelor's Degree",
    "8 कक्षा": "Basic Education (Up to Grade 8)",
    "9 class": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "Ied": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्‍नाक्तोर": "Master's Degree",
    "+2, उर्दु": "Higher Secondary / Intermediate (10+2 / PCL)",
    "७ कक्षा पास": "Basic Education (Up to Grade 8)",
    "१० कक्षा उतिर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "‍+2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नातकोउत्तर": "Master's Degree",
    "I.A.(+2)": "Higher Secondary / Intermediate (10+2 / PCL)",
    "I.A.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "B.Sc (Microbiology)": "Bachelor's Degree",
    "उच्च मा वि": "Higher Secondary / Intermediate (10+2 / PCL)",
    "M.ed": "Master's Degree",
    "टेष्ट पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "+२/ बि बि यस रनिङ ": "Bachelor's Degree",
    "दश पास ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "एस एल सि ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "साधारण लेखपढ ": "Literate / Non-Formal",
    "साधरण लेखपढ ": "Literate / Non-Formal",
    "एस.एल.सि. ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "Bsc Physics ": "Bachelor's Degree",
    "Intermediate (I.A.)": "Higher Secondary / Intermediate (10+2 / PCL)",
    "Chartered Accountant (M.Com)": "Master's Degree",
    "SLC Board of Nepal, +2 HSEB": "Higher Secondary / Intermediate (10+2 / PCL)",
    "बी.ई. (मेकानिकल)": "Bachelor's Degree",
    "Islington college BSc hons Compabing": "Bachelor's Degree",
    "आई.ए. स्सी. फरेष्ट्री": "Higher Secondary / Intermediate (10+2 / PCL)",
    "BSC (Bachelor in science)": "Bachelor's Degree",
    "५ कक्षा": "Basic Education (Up to Grade 8)",
    "सधारण लेख पढ": "Literate / Non-Formal",
    "समान्य ": "Literate / Non-Formal",
    "स्नातकोत्तर (अर्थ शास्त्र)": "Master's Degree",
    "सधारण लेखपढ ": "Literate / Non-Formal",
    "समान्य लेखपढ ": "Literate / Non-Formal",
    "प्रविणता प्रमाण पत्र ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "१० पास ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "12 कक्षा उत्तिण": "Higher Secondary / Intermediate (10+2 / PCL)",
    "see": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "BED": "Bachelor's Degree",
    "बि. एड.": "Bachelor's Degree",
    "बि. कम.": "Bachelor's Degree",
    "एम बि ए": "Master's Degree",
    "स्नातकोत्तर ": "Master's Degree",
    "बि बि एस र सिए फाइनल": "Bachelor's Degree",
    "बि एस सी आई टी ": "Bachelor's Degree",
    "दश": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "स्‍नातकोतर (M.A)": "Master's Degree",
    "BBA": "Bachelor's Degree",
    "7 पास": "Basic Education (Up to Grade 8)",
    "सिभिल ईन्जिनियर": "Bachelor's Degree",
    "C.A Final, B.com, BBS": "Bachelor's Degree",
    "स्‍नातकोतर (M.ED)": "Master's Degree",
    "SKLC": "Unspecified / Others",
    "10 पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "प्रविणता प्रमाण पत्र political science ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "पिचडी": "Doctorate / PhD",
    "आइ कम ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "सात पास ": "Basic Education (Up to Grade 8)",
    "बि फार्म": "Bachelor's Degree",
    "बि ए": "Bachelor's Degree",
    "IAK CTC": "Unspecified / Others",
    "निराक्षर ": "Illiterate",
    "विध्यावारिधी": "Doctorate / PhD",
    "I Com": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एसएलसी ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "डिग्री": "Bachelor's Degree",
    "एमवियस": "Master's Degree",
    "स्नातकोत्तर (कानून)": "Master's Degree",
    "८ कक्षा उत्तीर्ण": "Basic Education (Up to Grade 8)",
    "स्नातक रनिङ": "Bachelor's Degree",
    "स्नातकोत्तर, पि.एच.डि स्कलर": "Doctorate / PhD",
    "सिभिल इन्जिनियरिङ": "Bachelor's Degree",
    "९": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "आइ.ए.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "१२ उतिर्ण (बि.बि.एस. चौथो वर्ष रनिङ)": "Bachelor's Degree",
    "आइ एल": "Higher Secondary / Intermediate (10+2 / PCL)",
    "कक्षा ६": "Basic Education (Up to Grade 8)",
    "+ २ उत्तिण": "Higher Secondary / Intermediate (10+2 / PCL)",
    "phd": "Doctorate / PhD",
    "स्नातकोक्तर": "Master's Degree",
    "म्याट्रिक": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "ब्याचलर": "Bachelor's Degree",
    "जलस्रोत ईन्जिनियरिङमा डिग्री": "Bachelor's Degree",
    "पी.एच.डी. स्कलर": "Doctorate / PhD",
    "बि.एड.": "Bachelor's Degree",
    "दश कक्षा उत्तीर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "MA LLB": "Master's Degree",
    "8 Pass": "Basic Education (Up to Grade 8)",
    "8 pass ": "Basic Education (Up to Grade 8)",
    "Simple": "Literate / Non-Formal",
    "स्नातकोत्तर, राजनीतिक शास्त्र": "Master's Degree",
    "MSC": "Master's Degree",
    "स्वअध्ययन": "Literate / Non-Formal",
    "साक्षार": "Literate / Non-Formal",
    "MPA/BL": "Master's Degree",
    "B.L/M.Com (अध्ययनरत)": "Master's Degree",
    "स्नातकोत्तर (अंग्रेजी)": "Master's Degree",
    "एम वि ए": "Master's Degree",
    "+2 passed": "Higher Secondary / Intermediate (10+2 / PCL)",
    "१० ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "Bcahelor Of Medicine": "Bachelor's Degree",
    "कानूनमा स्नातक": "Bachelor's Degree",
    "आई.ए पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "९ पास.": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "प्राथमिक शिक्षा": "Basic Education (Up to Grade 8)",
    "I.com pass": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्तानतक ": "Bachelor's Degree",
    "मास्टर्स डिग्री शिक्षा संकाय": "Master's Degree",
    "IA pass": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आई ए पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "masters complete": "Master's Degree",
    "plus two": "Higher Secondary / Intermediate (10+2 / PCL)",
    "विद्यावारिधि (पढ्दै)": "Doctorate / PhD",
    "वि.एल.": "Bachelor's Degree",
    "आइ.ए ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "प्रविणता प्रमाणपत्र स्तर": "Higher Secondary / Intermediate (10+2 / PCL)",
    "बिद्याबारिधी": "Doctorate / PhD",
    "D.M.": "Master's Degree",
    "M.B.S.": "Master's Degree",
    "ATPL": "Unspecified / Others",
    "MA Economics": "Master's Degree",
    "BDS": "Bachelor's Degree",
    "अहेव": "Diploma / Certificate Level",
    "M.ED.": "Master's Degree",
    "M.BA.": "Master's Degree",
    "Bachelor of Medical Engineering": "Bachelor's Degree",
    "  १० कक्षा": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "S.L.C., C.M.A.": "Diploma / Certificate Level",
    "१० कक्षा": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "M.A./B.L": "Master's Degree",
    "SLC pass": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "10+2 pass": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्‍नातकोत्तर LLM": "Master's Degree",
    "स्‍नातकोत्तर तह": "Master's Degree",
    "सामान्य साक्षर": "Literate / Non-Formal",
    "स्नोकोत्तर": "Master's Degree",
    "ISc": "Higher Secondary / Intermediate (10+2 / PCL)",
    "BE electricals": "Bachelor's Degree",
    "बि एससी, एलएलबी (एभो)": "Bachelor's Degree",
    "एमबिइ एच": "Bachelor's Degree",
    "नौ कक्षा": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "बिए": "Bachelor's Degree",
    "आईए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "उच्च माध्यमिक तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एमए उर्दु": "Master's Degree",
    "वि.एस.सी.": "Bachelor's Degree",
    "बी.एस.सी.इलेक्ट्रिकल": "Bachelor's Degree",
    "वि.एस.सी.व.एल": "Bachelor's Degree",
    "अन्डर slc": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "पाँच कक्षा पास": "Basic Education (Up to Grade 8)",
    "माध्यमिक शिक्षा परिषद उत्तर प्रदेश": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "आधारभूत तह": "Basic Education (Up to Grade 8)",
    "5": "Basic Education (Up to Grade 8)",
    "स्‍नातोकत्तर": "Master's Degree",
    "S.L.C pass": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "B.L.": "Bachelor's Degree",
    "मास्टर्स ": "Master's Degree",
    "‍+2 पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "बी.ए.": "Bachelor's Degree",
    "एस.ई.ई": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "M.A., Bad": "Master's Degree",
    "स्नातक पास": "Bachelor's Degree",
    "वि.एस्सी. (एजी)": "Bachelor's Degree",
    "आधारभुत तह उत्तिर्ण": "Basic Education (Up to Grade 8)",
    "SLC पास (O लेभल र A लेभल)": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "विद्यावारीधी": "Doctorate / PhD",
    "स्नातकोत्तर (राजनीतिक शास्त्र)": "Master's Degree",
    "आइकम (I.com)": "Higher Secondary / Intermediate (10+2 / PCL)",
    "६ कक्षा पास": "Basic Education (Up to Grade 8)",
    "सात पास": "Basic Education (Up to Grade 8)",
    "एम.फिल.पिएचडी (शोधार्थी)": "Doctorate / PhD",
    "आई.एल.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "८ ": "Basic Education (Up to Grade 8)",
    "स्तानकोत्तर": "Master's Degree",
    "MA Economics MA Political Science": "Master's Degree",
    "एम.फिल.": "M.Phil",
    "I.ED.": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एम.ए. (राजनितिशास्त्र)": "Master's Degree",
    "MA, LLB, BSC": "Master's Degree",
    "B.Com पास": "Bachelor's Degree",
    "कक्षा १० उत्तिर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "IA पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "‌‌+२ पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "प्रा.वि.": "Basic Education (Up to Grade 8)",
    "‌+२ पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "८ कक्षा उत्तिर्ण": "Basic Education (Up to Grade 8)",
    "SLC उत्तिर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "I.A Pass +2": "Higher Secondary / Intermediate (10+2 / PCL)",
    "tslc": "Diploma / Certificate Level",
    "आइ.ए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आइ.एड": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नातक  तह": "Bachelor's Degree",
    "स्नातक राजनितिक रास्त्र": "Bachelor's Degree",
    "प्रमानपत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "med": "Master's Degree",
    "10+2 पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "bed pass": "Bachelor's Degree",
    "m. a pass ": "Master's Degree",
    "I.ed pass ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "test पास": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "B.ed pass ": "Bachelor's Degree",
    "12 pass ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "आइए": "Higher Secondary / Intermediate (10+2 / PCL)",
    "एमफिल": "M.Phil",
    "M.Ed.": "Master's Degree",
    "S.L.C ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "B.Com": "Bachelor's Degree",
    "S.L.C. pass": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "स्नातकत्तोर": "Master's Degree",
    "३ कक्षा पास": "Basic Education (Up to Grade 8)",
    "आई एल अध्ययन": "Higher Secondary / Intermediate (10+2 / PCL)",
    "‌आईएड पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "‌‌+2 pass": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नातक तह उत्तीर्ण": "Bachelor's Degree",
    "दश कक्षा अनुर्तिर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "अण्डर एस एल सी": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "आइ ए पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "12 उत्तीर्ण": "Higher Secondary / Intermediate (10+2 / PCL)",
    "9 कक्षा उत्तिर्ण": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "PCL(+2)": "Higher Secondary / Intermediate (10+2 / PCL)",
    "BACHELOR": "Bachelor's Degree",
    "slc ": "Secondary Education (Grade 9-10 / SLC / SEE)",
    "B com": "Bachelor's Degree",
    "विद्यावारिधि, वि.एल.": "Doctorate / PhD",
    "Bachelor ": "Bachelor's Degree",
    "B.L Pass ": "Bachelor's Degree",
    "master ": "Master's Degree",
    "Bachelor pass ": "Bachelor's Degree",
    "Bacherlor ": "Bachelor's Degree",
    "राजनिति शास्त्र एम ए": "Master's Degree",
    "एम वि एस": "Master's Degree",
    "स्नताक": "Bachelor's Degree",
    "MA BL": "Master's Degree",
    "आईकम पास": "Higher Secondary / Intermediate (10+2 / PCL)",
    "I ED": "Higher Secondary / Intermediate (10+2 / PCL)",
    "स्नात्तकोत्तर": "Master's Degree",
    "बिएल एमपिए एमबिए ": "Master's Degree",
    "सामान्य लेखपण": "Literate / Non-Formal",
    "प्रविणतापत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "भेटनरी,जेटिए": "Diploma / Certificate Level",
    "FY Bcom": "Bachelor's Degree",
    "+2 प्रमाणपत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "B Com": "Bachelor's Degree",
    "विद्यावारिधि (PHD)": "Doctorate / PhD",
    "MSC yoga and science.": "Master's Degree",
    "एम फिल पि एच डि.": "Doctorate / PhD",
    "आठ कक्षा पास": "Basic Education (Up to Grade 8)",
    "स्नातोकोत्तर": "Master's Degree",
    "बी फारमेसी": "Bachelor's Degree",
    "कक्षा ५ ": "Basic Education (Up to Grade 8)",
    "स्ननातोकोत्तर": "Master's Degree",
    "उच्च शिक्षा ": "Higher Secondary / Intermediate (10+2 / PCL)",
    "विदया वारिणी": "Doctorate / PhD",
    "BSc AG": "Bachelor's Degree",
    "PHD Scholar": "Doctorate / PhD",
    "डिप्लोमा (ओभरसियर्स)": "Diploma / Certificate Level",
    "प्रविणाता प्रमाण पत्र तह": "Higher Secondary / Intermediate (10+2 / PCL)",
    "मास्टर्स डिग्री": "Master's Degree",
    "एम.ए. समाजशास्त्र": "Master's Degree",
    "M.A. Civil sub engeneer": "Master's Degree",
    "आठ कक्षा उतिर्ण": "Basic Education (Up to Grade 8)"
}

- *Here, I used AI tools (**ChatGPT**) to translate all words, making the process faster and more efficient.*

In [54]:
df1['education_category'] = df1['qualification'].map(education_category_mapping)

In [55]:
df1['education_category'].value_counts()

education_category
Secondary Education (Grade 9-10 / SLC / SEE)    739
Higher Secondary / Intermediate (10+2 / PCL)    626
Bachelor's Degree                               564
Master's Degree                                 343
Literate / Non-Formal                           263
Basic Education (Up to Grade 8)                  99
Doctorate / PhD                                  59
Diploma / Certificate Level                      26
Illiterate                                       13
Unspecified / Others                              9
M.Phil                                            8
Name: count, dtype: int64

In [56]:
df1['education_category'].isna().sum()

np.int64(657)

### `address`

In [ ]:
# Installing new library

!uv add deep-translator

Resolved 121 packages in 1.67s
Prepared 1 package in 152ms
warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 194ms
 + deep-translator==1.11.4

#### **row-by-row translation**

In [67]:
from deep_translator import GoogleTranslator    # for translation

In [74]:
# # 1. Create a translator tool that changes Nepali words into English
# nep_to_eng = GoogleTranslator(source='ne', target='en')

# # 2. Apply the translation to the column/series
# trans_address = address.apply(lambda x: nep_to_eng.translate(x) if pd.notna(x) else x)

In [ ]:
# # Making a dictionary object by using two series.

# # 1. zip(): Pairs each original address with its English translation by row position
# # 2. dict(): Converts those pairs into a key-value lookup dictionary

# address_map = dict(zip(address, trans_address))

# df1['address'] = df1['address'].map(address_map)

#### **batch processing (translation)**

In [75]:
nep_to_eng = GoogleTranslator(source='ne', target='en')

# 1. Get unique, non-null address values to save time and API quota
unique_addresses = df1['address'].dropna().unique().tolist()

# 2. Translate in batches of 50 to avoid request payload limits
batch_size = 50
translated_dict = {}

for i in range(0, len(unique_addresses), batch_size):
    batch = unique_addresses[i:i + batch_size]
    try:
        # Translate the whole list at once
        translations = nep_to_eng.translate_batch(batch)
        # Map original Nepali word to English translation
        for nep, eng in zip(batch, translations):
            translated_dict[nep] = eng
    except Exception as e:
        print(f"Error at batch {i}: {e}")
        # Fallback: if batch fails, keep original Nepali text for this batch
        for nep in batch:
            translated_dict[nep] = nep

- *This step takes about **21 minutes** to run. To save time, I did not perform it in the previous steps and executed it only when necessary.*

In [81]:
# 3. Map the translations back to your original series
df1['address'] = df1['address'].map(translated_dict)

In [82]:
df1['address'].value_counts()

address
Kathmandu                                                                 121
Rupandehi                                                                  83
Mahottari                                                                  77
Siraha                                                                     76
Sarlahi                                                                    71
                                                                         ...
Nawalparasi (Bardghat Susta West) Ramgram Municipality Piprahiya            1
Nawalparasi (Bardghat Susta West) Sunwal Municipality Sundarvasti           1
Navalparasi (Bardghat Susta West) Palhinandan Rural Municipality Palhi      1
Nawalparasi (Bardghat Susta West) Sunwal Municipality Mangalnagar           1
Jhapa Mechinagar Municipality Ward Khal                                     1
Name: count, Length: 1426, dtype: int64

In [83]:
df1.head()

,candidateId,candidate,AGE_YR,partyName,partyId,votes,gender,isWinner,fatherName,qualification,...,address,spouseName,experience,code,province,district,constituency,votesCast,totalVoters,education_category
0,339933,Khitiz Thebe,38,Nepal Communist Party (Ekikrit Marxbadi Leninb...,2598.0,13962,M,True,भुपेन्द्र थेबे,स्नातक,...,Taplejung Sirijungha Rural Municipality Madibung,NaN,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree
1,341131,Gajendra Prasad Tumyang Limbu,46,Nepali Congress,2583.0,11711,M,False,Purna Bahadur Limbu,स्नातक,...,Taplejung,Radhika Lingden Tumyang,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree
2,339610,Khel Prasad Buda Chhetri,50,Nepali Communist Party,2557.0,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,...,Taplejung Sirijungha Rural Municipality Chichi...,कुमारी बुडाक्षेत्री,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308,Higher Secondary / Intermediate (10+2 / PCL)
3,340005,Santosh Rai,49,Shram Sanskriti Party,2501.0,5209,M,False,Bal Bahadur Rai,कक्षा ८,...,Taplejung,Sita Rai,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308,Basic Education (Up to Grade 8)
4,340459,Birendra Shrestha,55,Rastriya Swatantra Party,2528.0,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,...,Taplejung,Manolak Wuphashree Shrestha,NaN,1-ताप्लेजुङ-1,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree

In [84]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   candidateId         3406 non-null   int64
 1   candidate           3406 non-null   object
 2   AGE_YR              3406 non-null   int64
 3   partyName           3406 non-null   object
 4   partyId             2263 non-null   float64
 5   votes               3406 non-null   int64
 6   gender              3406 non-null   object
 7   isWinner            3406 non-null   bool
 8   fatherName          3405 non-null   object
 9   qualification       2762 non-null   object
 10  institution         1769 non-null   object
 11  address             3406 non-null   object
 12  spouseName          2595 non-null   object
 13  experience          1083 non-null   object
 14  code                3406 non-null   object
 15  province            3406 non-null   object
 16  district            3406 non-null   object
 17  constituency        3406 non-null   object
 18  votesCast           3406 non-null   int64
 19  totalVoters         3406 non-null   int64
 20  education_category  2749 non-null   object
dtypes: bool(1), float64(1), int64(5), object(14)
memory usage: 535.6+ KB

# Data cleaning 2.0

## **Load coordinates data**

In [85]:
coordinates = pd.read_csv("constituency_coordinates.csv")

In [86]:
coordinates.head()

         Constituency Name  Latitude  Longitude
0  ताप्लेजुङ क्षेत्र नं. 1   27.3500    87.6667
1     पाँचथर क्षेत्र नं. 1   27.2167    87.8000
2       इलाम क्षेत्र नं. 1   26.9167    88.0000
3       इलाम क्षेत्र नं. 2   26.9000    87.8500
4       झापा क्षेत्र नं. 1   26.6333    88.0833

In [87]:
coordinates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Constituency Name  165 non-null    object
 1   Latitude           165 non-null    float64
 2   Longitude          165 non-null    float64
dtypes: float64(2), object(1)
memory usage: 4.0+ KB

- *The coordinate data was initially identified using **ChatGPT** and then verified before being used in the analysis.*

## Merge tables (**coordinates** + **constituency**)

In [88]:
temp = coordinates.merge(constituencies, how='inner', left_on='Constituency Name', right_on='nameNp')

In [89]:
temp = temp[['code','Latitude','Longitude']]

In [90]:
temp

                                     code  Latitude  Longitude
0                           1-ताप्लेजुङ-1   27.3500    87.6667
1                              1-पाँचथर-1   27.2167    87.8000
2                                1-इलाम-1   26.9167    88.0000
3                                1-इलाम-2   26.9000    87.8500
4                                1-झापा-1   26.6333    88.0833
..                                    ...       ...        ...
160                          7-कञ्चनपुर-2   28.9000    80.2667
161                          7-कञ्चनपुर-3   28.8500    80.1833
162  5-नवलपरासी (बर्दघाट सुस्ता पश्चिम)-1   27.5333    83.7500
163  5-नवलपरासी (बर्दघाट सुस्ता पश्चिम)-2   27.5167    83.6500
164                6-रुकुम (पश्चिम भाग)-1   28.6500    82.4500

[165 rows x 3 columns]

## Merge tables (**df1** + **temp**)

In [91]:
df1 = df1.merge(temp, on='code')

## Select required cols

In [92]:
df1.columns

Index(['candidateId', 'candidate', 'AGE_YR', 'partyName', 'partyId', 'votes',
       'gender', 'isWinner', 'fatherName', 'qualification', 'institution',
       'address', 'spouseName', 'experience', 'code', 'province', 'district',
       'constituency', 'votesCast', 'totalVoters', 'education_category',
       'Latitude', 'Longitude'],
      dtype='object')

In [93]:
selected_cols = [
    'candidateId','candidate','AGE_YR','partyName','partyId', 'votes',
    'gender','isWinner', 'fatherName', 
    'qualification', 'institution', 'address',
    'spouseName', 'experience','province', 'district',
    'constituency', 'votesCast', 'totalVoters', 'education_category',
    'Latitude', 'Longitude'
    ]

In [94]:
df1 = df1[selected_cols]

In [95]:
df1.head()

,candidateId,candidate,AGE_YR,partyName,partyId,votes,gender,isWinner,fatherName,qualification,...,spouseName,experience,province,district,constituency,votesCast,totalVoters,education_category,Latitude,Longitude
0,339933,Khitiz Thebe,38,Nepal Communist Party (Ekikrit Marxbadi Leninb...,2598.0,13962,M,True,भुपेन्द्र थेबे,स्नातक,...,NaN,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667
1,341131,Gajendra Prasad Tumyang Limbu,46,Nepali Congress,2583.0,11711,M,False,Purna Bahadur Limbu,स्नातक,...,Radhika Lingden Tumyang,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667
2,339610,Khel Prasad Buda Chhetri,50,Nepali Communist Party,2557.0,6775,M,False,शम्सेर बहादुर बुडाक्षेत्री,I.s.c,...,कुमारी बुडाक्षेत्री,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Higher Secondary / Intermediate (10+2 / PCL),27.35,87.6667
3,340005,Santosh Rai,49,Shram Sanskriti Party,2501.0,5209,M,False,Bal Bahadur Rai,कक्षा ८,...,Sita Rai,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Basic Education (Up to Grade 8),27.35,87.6667
4,340459,Birendra Shrestha,55,Rastriya Swatantra Party,2528.0,4155,M,False,Tek Bahadur Shrestha,ईन्जिनेरिङ ग्राजुएड,...,Manolak Wuphashree Shrestha,NaN,Koshi,Taplejung,Taplejung-1,42897,90308,Bachelor's Degree,27.35,87.6667

## Rename cols

In [96]:
# Initial cols
df1.columns

Index(['candidateId', 'candidate', 'AGE_YR', 'partyName', 'partyId', 'votes',
       'gender', 'isWinner', 'fatherName', 'qualification', 'institution',
       'address', 'spouseName', 'experience', 'province', 'district',
       'constituency', 'votesCast', 'totalVoters', 'education_category',
       'Latitude', 'Longitude'],
      dtype='object')

In [97]:
# Rename cols
df1.columns = ['candidate_id', 'candidate', 'age', 'party', 'party_id', 'votes', 'gender',
       'is_winner', 'father', 'qualification', 'institution', 'address',
       'spouse', 'experience', 'province', 'district', 'constituency',
       'votes_cast', 'total_voters', 'education_category', 'latitude',
       'longitude']

# Eport into CSV file

In [98]:
df1.to_csv("cleaned_data.csv")